'use strict';
(function(){
if(new URLSearchParams(location.search).has('obs'))return;
const main=document.querySelector('main'),nav=document.querySelector('.app-nav'),brand=document.querySelector('.brand');
const labels={overview:'直播總覽',events:'支持紀錄',records:'頻道與直播',ranking:'排行榜',settings:'OBS 外觀與輸出',exports:'匯出與備份',appearance:'統計與一般設定'};
nav.prepend(brand);const navCaption=document.createElement('p');navCaption.className='creator-nav-caption';navCaption.textContent='你的直播空間';brand.after(navCaption);
for(const [id,label]of Object.entries(labels)){const b=nav.querySelector('[data-tab="'+id+'"]');b.textContent=label;nav.append(b);}
const crumb=document.createElement('div');crumb.className='creator-breadcrumb';crumb.textContent='直播空間 / 直播總覽';document.querySelector('.topbar').prepend(crumb);
const sidebarNote=document.createElement('div');sidebarNote.className='creator-sidebar-note';sidebarNote.textContent='紀錄只存本機。背景啟用後，關閉管理頁仍持續收錄。';nav.append(sidebarNote);
const studio=document.createElement('section');studio.id='studio';studio.hidden=true;studio.innerHTML=RankStudioTemplate();
main.append(studio);
const kindLabels={sc:'SC',gift:'贈送會員',jewel:'寶石'},periodLabels={current:'本場',monthly:'本月',all_time:'累計'};
function boardLabel(kind,period){return periodLabels[period]+' '+kindLabels[kind];}
function boardTitle(kind,period){return RankTheme.select(StyleStore.styles,kind,period).titles?.[period]||boardLabel(kind,period)+' 排行榜';}
function identity(){studio.querySelector('.panel-heading h2').textContent=$('themeTitle_'+activePeriod).value||boardLabel(activeKind,activePeriod)+' 排行榜';studio.querySelector('.panel-heading p').textContent=boardLabel(activeKind,activePeriod)+' · 修改只套用到這張榜';for(const p of RankTheme.periods)$('themeTitle_'+p).closest('label').hidden=p!==activePeriod;}
function fillBoard(){fill(RankTheme.select(StyleStore.styles,activeKind,activePeriod));identity();}
async function copyBoardUrl(kind,period){try{const url=ObsOutput.url(kind,period);try{await navigator.clipboard.writeText(url);}catch{const box=document.createElement('textarea');box.value=url;box.style.cssText='position:fixed;left:-10000px';document.body.append(box);box.select();const ok=document.execCommand('copy');box.remove();if(!ok)throw Error('無法自動複製，請展開卡片的網址手動複製');}showToast('已複製 '+boardLabel(kind,period)+' 的 OBS 網址');}catch(e){showToast(e.message);}}
const boardNodes=[];
for(const kind of RankTheme.kinds){const section=document.createElement('section');section.className='board-group';const heading=document.createElement('h3');heading.textContent=kindLabels[kind];const grid=document.createElement('div');grid.className='board-grid';section.append(heading,grid);for(const period of RankTheme.periods){const card=document.createElement('article');card.className='board-card';card.dataset.board=kind+':'+period;const label=document.createElement('span');label.className='board-badge';label.textContent=boardLabel(kind,period);const title=document.createElement('h4');const note=document.createElement('p');note.className='creator-help';const actions=document.createElement('div');actions.className='board-actions';const edit=document.createElement('button');edit.type='button';edit.className='btn btn-primary board-edit';edit.textContent='設定與預覽';edit.setAttribute('aria-label','設定 '+boardLabel(kind,period));edit.onclick=()=>openStudio(kind,period);const copy=document.createElement('button');copy.type='button';copy.className='btn btn-outline-secondary board-copy';copy.textContent='複製 OBS 網址';copy.onclick=()=>copyBoardUrl(kind,period);const detail=document.createElement('details'),summary=document.createElement('summary'),url=document.createElement('input');detail.className='board-url creator-help';summary.textContent='檢視網址';url.className='form-control';url.readOnly=true;url.setAttribute('aria-label',boardLabel(kind,period)+' OBS 網址');detail.append(summary,url);actions.append(edit,copy);card.append(label,title,note,actions,detail);grid.append(card);boardNodes.push({kind,period,title,note,copy,url});}$('obsBoards').append(section);}
function refreshBoards(){for(const item of boardNodes){item.title.textContent=boardTitle(item.kind,item.period);const style=RankTheme.select(StyleStore.styles,item.kind,item.period);item.note.textContent='獨立設定 · '+(style.top?'前 '+style.top+' 名':'名次沿用既有網址');item.copy.disabled=!globalThis.ObsOutput?.ready;item.url.value=globalThis.ObsOutput?.ready?ObsOutput.url(item.kind,item.period):'等待背景輸出連線';}}
window.addEventListener('obs-links-updated',refreshBoards);window.addEventListener('rank-style-saved',refreshBoards);
const previewStyle=document.createElement('style');previewStyle.id='creatorPreviewStyle';document.head.append(previewStyle);
const partsLabels={title:'榜單標題',number:'名次數字',name:'聊天室名稱',value:'金額／數量'};
for(const [p,label]of Object.entries(partsLabels)){const row=document.createElement('div');row.className='creator-part';row.innerHTML='<strong>'+label+'</strong><input class="form-control" data-theme-font="'+p+'" list="installedFontNames" aria-label="'+label+'字型" placeholder="沿用整體" maxlength="100"><label class="creator-check"><input type="checkbox" data-theme-custom="'+p+'">自訂色</label><input type="color" data-theme-color="'+p+'" aria-label="'+label+'顏色" value="#e8bc72">';$('themeParts').append(row);}
RankFontPicker.attach($('themeFont'));for(const input of document.querySelectorAll('[data-theme-font]'))RankFontPicker.attach(input);
RankStudioEmoji.mount($);
const canvasFields=['canvasMode','canvasWidth','canvasHeight','backgroundFit','backgroundWidth','backgroundHeight','backgroundLock','backgroundX','backgroundY'];
const canvasId=key=>'theme'+key[0].toUpperCase()+key.slice(1);
let activePeriod='monthly',draftStyleRevision='',activeKind='sc',dirty=false,loadingAsset=false,currentDraft=RankTheme.normalize({enabled:true,size:1.5}),saveBusy=false;
function notice(message){$('themeNotice').textContent=message;}
function hasDraft(){return !dirty||confirm('外觀草稿還沒套用。要放棄這次調整嗎？');}
function switchPage(id){if(!labels[id]&&id!=='studio')return;if(!studio.hidden&&id!=='studio'&&!hasDraft())return;main.querySelectorAll(':scope > section').forEach(s=>s.hidden=s.id!==id);nav.querySelectorAll('[data-tab]').forEach(b=>{const selected=b.dataset.tab===(id==='studio'?'settings':id);b.classList.toggle('active',selected);b.setAttribute('aria-current',selected?'page':'false');});crumb.textContent='直播空間 / '+(id==='studio'?'OBS 外觀與輸出 / 調整外觀':labels[id]);main.scrollTop=0;if(id!=='studio')dirty=false;if(id==='studio')draw();}
nav.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>switchPage(b.dataset.tab));$('studioBack').onclick=()=>switchPage('settings');
function readDraft(){const s={...currentDraft,top:Number($('studioTop').value),enabled:true,theme:$('themeForm').elements.theme.value,font:$('themeFont').value,size:Number($('themeSize').value),accent:$('themeAccent').value,layout:$('themeLayout').value,valuePosition:Number($('themeValuePosition').value),rankGap:Number($('themeRankGap').value),valueGap:Number($('themeValueGap').value),rowGap:Number($('themeRowGap').value),maxNameLength:Number($('themeMaxNameLength').value),hideAtPrefix:$('themeHideAtPrefix').checked,showTitle:$('themeTitle').checked,medals:$('themeMedals').checked,rankMode:$('themeRankMode').value,iconSize:Number($('themeIconSize').value),parts:{}};for(const p of RankTheme.parts)s.parts[p]={font:document.querySelector('[data-theme-font="'+p+'"]').value,color:document.querySelector('[data-theme-custom="'+p+'"]').checked?document.querySelector('[data-theme-color="'+p+'"]').value:''};s.icons={};for(const i of [1,2,3])s.icons[i]={emoji:$('rankEmoji'+i).value};s.titles={};for(const period of ['current','monthly','all_time'])s.titles[period]=$('themeTitle_'+period).value;for(const key of canvasFields){const input=$(canvasId(key));s[key]=input.type==='checkbox'?input.checked:input.type==='number'||input.type==='range'?Number(input.value):input.value;}s.fontAssets={...currentDraft.fontAssets};s.fontSources={...currentDraft.fontSources};for(const name of [s.font,...Object.values(s.parts).map(p=>p.font)]){const data=RankFontPicker.assetFor(name);if(data)s.fontAssets[name]=data;const sources=RankFontPicker.sourcesFor(name);if(sources.length)s.fontSources[name]=sources;}return RankTheme.normalize(s);}
function fill(value){draftStyleRevision=StyleStore.remoteRevision;currentDraft=RankTheme.normalize(value);$('studioTop').value=String(currentDraft.top||10);$('themeRankMode').value=currentDraft.rankMode;$('themeIconSize').value=currentDraft.iconSize;for(const i of [1,2,3])$('rankEmoji'+i).value=currentDraft.icons[i].emoji;for(const period of ['current','monthly','all_time'])$('themeTitle_'+period).value=currentDraft.titles[period];for(const key of canvasFields){const input=$(canvasId(key));if(input.type==='checkbox')input.checked=currentDraft[key];else input.value=currentDraft[key];}$('themeForm').elements.theme.value=currentDraft.theme;$('themeFont').value=currentDraft.font;$('themeSize').value=currentDraft.size;$('themeAccent').value=currentDraft.accent;$('themeLayout').value=currentDraft.layout;$('themeValuePosition').value=currentDraft.valuePosition;$('themeRankGap').value=currentDraft.rankGap;$('themeValueGap').value=currentDraft.valueGap;$('themeRowGap').value=currentDraft.rowGap;$('themeMaxNameLength').value=currentDraft.maxNameLength;$('themeHideAtPrefix').checked=currentDraft.hideAtPrefix;$('themeTitle').checked=currentDraft.showTitle;$('themeMedals').checked=currentDraft.medals;for(const p of RankTheme.parts){document.querySelector('[data-theme-font="'+p+'"]').value=currentDraft.parts[p].font;document.querySelector('[data-theme-custom="'+p+'"]').checked=!!currentDraft.parts[p].color;document.querySelector('[data-theme-color="'+p+'"]').value=currentDraft.parts[p].color||currentDraft.accent;}$('themeImageName').textContent=currentDraft.imageName||'使用版型底色';$('themeFontName').textContent=currentDraft.fontName||'未匯入，使用電腦已安裝字型';dirty=false;$('studioSavedState').textContent=value?.enabled?'已載入已保存的外觀':'外觀草稿，尚未套用';draw();}
function draw(){if(studio.hidden)return;identity();const draft=readDraft(),period=activePeriod,top=Number($('studioTop').value),rows=$('studioMockTen').checked?Array.from({length:10},(_,i)=>({displayName:'示意支持者 '+(i+1),value:activeKind==='sc'?1000-i*50:10-i})):rowsFor(activeKind,period,top);const view=RankOutput.presentation(rows,activeKind,period,{...state.settings,showTitle:true,truncateNames:true,maxNameLength:draft.maxNameLength,hideAtPrefix:draft.hideAtPrefix,customTitle:draft.titles[period]});ObsRenderer.render($('studioPreview'),view,RankOutput.asText(view),activeKind);$('themeValueGap').closest('label').hidden=draft.layout==='aligned';$('themeValuePosition').closest('label').hidden=draft.layout!=='aligned';$('themeValuePositionValue').textContent=draft.valuePosition+'%';const css=RankTheme.css(draft,'#studioPreview');if(previewStyle.textContent!==css)previewStyle.textContent=css;$('themeSizeValue').textContent=draft.size+' em';for(const [id,key]of [['RankGap','rankGap'],['ValueGap','valueGap'],['RowGap','rowGap']])$('theme'+id+'Value').textContent=draft[key]+' em';$('studioDataLabel').textContent=$('studioMockTen').checked?'示意資料 · 不會送至 OBS':'使用已收到的真實紀錄';$('studioEmpty').textContent=$('studioMockTen').checked?'僅供排版的 10 列示意；儲存只保存外觀，正式榜單仍使用真實紀錄。':rows.length?'預覽 '+rows.length+' 名 · 未套用的調整不影響 OBS':'這個期間沒有可計入的紀錄。仍可調整版型；不會加入假資料。';$('themeIconSizeValue').textContent=draft.iconSize+' em';$('selectedFontSample').style.fontFamily=(draft.fontData?'"studioPreviewImported",':'')+(draft.font?(draft.fontSources[draft.font]?.length||draft.fontAssets[draft.font]?'"studioPreviewLocal0",':JSON.stringify(draft.font)+','):'')+'"Microsoft JhengHei",sans-serif';checkFontRendering(draft);updateCanvas(draft);}
const checkFontRendering=createRankFontPreview($,{getDraft:()=>currentDraft,draw,partsLabels});
async function openStudio(kind,period='current'){if(!RankTheme.kinds.includes(kind)||!RankTheme.periods.includes(period)||saveBusy||loadingAsset)return;if(!studio.hidden&&!hasDraft())return;try{await StyleStore.ready;activeKind=kind;activePeriod=period;$('studioMockTen').checked=false;fillBoard();switchPage('studio');selectEditorTab('content');$('applyTheme').disabled=false;notice('');}catch(e){showToast('無法讀取已保存外觀：'+e.message);}}
$('studioTop').onchange=()=>{dirty=true;$('studioSavedState').textContent='尚未儲存';draw();};$('studioMockTen').onchange=draw;
$('themeForm').onsubmit=e=>e.preventDefault();$('themeForm').addEventListener('input',e=>{if(e.target.type==='file')return;if(e.target.id==='themeFont'&&currentDraft.fontData){currentDraft={...currentDraft,fontData:'',fontName:''};$('themeFontFile').value='';$('themeFontName').textContent='改用選擇的本機字型；匯入字型已從草稿移除';}if(e.target.dataset.themeColor)document.querySelector('[data-theme-custom="'+e.target.dataset.themeColor+'"]').checked=true;dirty=true;$('studioSavedState').textContent='外觀草稿尚未套用';draw();});
async function save(enabled=true){if(saveBusy||loadingAsset)return;saveBusy=true;$('applyTheme').disabled=true;try{const startKind=activeKind,startPeriod=activePeriod,before=readDraft();notice('正在準備外觀與字型…');await Promise.allSettled([before.font,...RankTheme.parts.map(p=>before.parts[p].font)].filter(Boolean).map(name=>RankFontPicker.loadFace(name,before.fontSources[name],before.fontAssets[name])));if(startKind!==activeKind||startPeriod!==activePeriod)throw Error('榜單或期間已切換，請重新套用目前草稿');const draft=readDraft();draft.enabled=enabled;await StyleStore.save(activeKind,draft,draftStyleRevision,activePeriod);draftStyleRevision=StyleStore.remoteRevision;currentDraft=draft;dirty=false;$('studioSavedState').textContent='已儲存在本機';notice(enabled?'已套用至 '+boardLabel(activeKind,activePeriod)+'，其他榜未更動。':'已恢復原始透明輸出，原有 OBS 自訂 CSS 仍保留。');$('publishObs').click();showToast('外觀已保存；等待 OBS 同步');}catch(e){notice('保存失敗，未更動原有外觀：'+e.message);}finally{saveBusy=false;$('applyTheme').disabled=!StyleStore.loaded;}}
$('applyTheme').onclick=()=>save(true);$('disableTheme').onclick=()=>{if(confirm('恢復這張榜的原始透明輸出？事件與其他榜單不受影響。'))save(false);};$('resetThemeDraft').onclick=()=>{if(hasDraft()){fill({enabled:true,size:1.5});dirty=true;$('studioSavedState').textContent='重設草稿尚未套用';}};
RankStudioEmoji.bind($,()=>{dirty=true;$('studioSavedState').textContent='尚未儲存';draw();});
document.fonts.addEventListener('loadingdone',()=>{if(!studio.hidden)updateCanvas(readDraft());});
function fileData(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(reader.error);reader.readAsDataURL(file);});}
async function loadAsset(file,type){if(!file||loadingAsset)return;loadingAsset=true;$('applyTheme').disabled=true;try{const startKind=activeKind;if(file.size>(type==='image'?2:32)*1024*1024)throw Error(type==='image'?'圖片請選擇 2 MB 以內':'字型請選擇 32 MB 以內');let url=await fileData(file);if(type==='image'){if(!['image/png','image/jpeg','image/webp'].includes(file.type))throw Error('只接受 PNG、JPG、WebP');await new Promise((resolve,reject)=>{const img=new Image();img.onload=resolve;img.onerror=()=>reject(Error('圖片無法讀取'));img.src=url;});}else{const ext=file.name.split('.').at(-1).toLowerCase();if(!['woff','woff2','ttf','otf'].includes(ext))throw Error('不支援的字型格式');url='data:font/'+ext+';base64,'+url.split(',')[1];await new FontFace('RankFontValidation','url("'+url+'")').load();}if(startKind!==activeKind)throw Error('榜單已切換，請重新選擇檔案');if(type==='font')$('themeFont').value='';currentDraft=RankTheme.normalize({...readDraft(),[type==='image'?'image':'fontData']:url,[type==='image'?'imageName':'fontName']:file.name});$(type==='image'?'themeImageName':'themeFontName').textContent=file.name;dirty=true;$('studioSavedState').textContent='新資源尚未套用';notice('已載入 '+file.name+'，按儲存並套用才會保存並同步。');draw();}catch(e){notice('載入失敗：'+e.message);}finally{loadingAsset=false;$('applyTheme').disabled=!StyleStore.loaded;}}
$('themeImageFile').onchange=()=>loadAsset($('themeImageFile').files[0],'image');$('themeFontFile').onchange=()=>loadAsset($('themeFontFile').files[0],'font');
$('removeThemeImage').onclick=()=>{currentDraft={...readDraft(),image:'',imageName:''};$('themeImageName').textContent='使用版型底色';$('themeImageFile').value='';dirty=true;draw();};$('removeThemeFont').onclick=()=>{currentDraft={...readDraft(),fontData:'',fontName:''};$('themeFontName').textContent='未匯入，使用電腦已安裝字型';$('themeFontFile').value='';dirty=true;draw();};
function updateCanvas(draft){updateRankCanvas(draft,$,canvasId);}
window.addEventListener('resize',()=>{if(!studio.hidden)draw();});
const cssDialog=document.createElement('dialog');cssDialog.className='creator-css-dialog';cssDialog.innerHTML='<div class="inspector-heading"><h2>OBS 自訂 CSS</h2><button type="button" class="btn btn-outline-secondary" id="closeThemeCss">關閉</button></div><p>複製到 OBS 瀏覽器來源的「自訂 CSS」。包含目前背景與匯入字型時，檔案可能較大；分享前請確認授權。</p><textarea id="themeCssText" spellcheck="false" aria-label="OBS 自訂 CSS"></textarea><div class="action-row"><button type="button" id="copyThemeCss" class="btn btn-primary">複製 CSS</button><button type="button" id="downloadThemeCss" class="btn btn-outline-secondary">下載 CSS</button></div><p id="themeCssNotice" role="status"></p>';document.body.append(cssDialog);
$('themeCss').onclick=()=>{$('themeCssText').value='html,body{margin:0;background:transparent;overflow:hidden;}\n'+RankTheme.css(readDraft());$('themeCssNotice').textContent='';cssDialog.showModal();};$('closeThemeCss').onclick=()=>cssDialog.close();$('copyThemeCss').onclick=async()=>{try{await navigator.clipboard.writeText($('themeCssText').value);$('themeCssNotice').textContent='CSS 已複製';}catch{$('themeCssText').focus();$('themeCssText').select();$('themeCssNotice').textContent='已選取 CSS，請按 Ctrl+C 複製。';}};$('downloadThemeCss').onclick=()=>{const url=URL.createObjectURL(new Blob([$('themeCssText').value],{type:'text/css;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='yt-rank-show-'+activeKind+'-style.css';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};

const rankingStyle=document.createElement('button');rankingStyle.type='button';rankingStyle.className='btn btn-outline-secondary creator-rank-style';rankingStyle.textContent='調整這張榜的外觀 ↗';rankingStyle.onclick=()=>openStudio($('kind').value,$('period').value);document.querySelector('.ranking-controls').after(rankingStyle);
$('scanFonts').onclick=async()=>{const button=$('scanFonts'),status=$('fontScanNotice');button.disabled=true;status.textContent='正在讀取本機字型…';try{const result=await LocalRuntime.request('/fonts');if(!Array.isArray(result.fonts))throw Error(result.error||'請更新本機同步器');const count=RankFontPicker.setCatalog(result.fonts);status.textContent='已讀取 '+count+' 種字型，可搜尋名稱、別名並試看。';if(!studio.hidden){dirty=true;$('studioSavedState').textContent='字型載入規則尚未套用';draw();}}catch(e){status.textContent='讀取失敗：'+e.message+'。仍可手動輸入或匯入字型。';}finally{button.disabled=false;}};
// Move existing controls, preserving their IDs and original handlers / statistics code.
const appearance=$('appearancePanel');appearance.querySelector('h2').textContent='統計與一般設定';appearance.querySelector(':scope > summary').textContent='統計與一般設定';appearance.querySelector('.panel-heading p').textContent='幣別與資料用途和外觀分開管理。';const mode=$('recordMode').closest('label');appearance.querySelector('#settingsForm').before(mode);const advanced=$('settingsForm').querySelector('details');advanced.querySelector('summary').textContent='幣別設定';
const txtOptions=document.createElement('details');txtOptions.id='txtOnlySettings';txtOptions.className='advanced-block';const txtSummary=document.createElement('summary');txtSummary.textContent='純文字輸出（TXT）';txtOptions.append(txtSummary);const txtHelp=document.createElement('p');txtHelp.className='creator-help';txtHelp.textContent='只用於 TXT、原始未套用外觀的輸出及文字排行榜預覽。已套用外觀的 OBS 請在工作室調整。';txtOptions.append(txtHelp);const txtGrid=document.createElement('div');txtGrid.className='form-grid';txtOptions.append(txtGrid);for(const name of ['rankNameSpaces','nameValueSpaces','blankLines','maxNameLength'])txtGrid.append($('settingsForm').querySelector('[name="'+name+'"]').closest('label'));txtOptions.append($('settingsForm').querySelector('[name="showTitle"]').closest('label'));txtOptions.append($('outputPath'));for(const input of txtOptions.querySelectorAll('input,select')){input.setAttribute('form','settingsForm');for(const event of ['input','change'])input.addEventListener(event,()=>{$('settingsForm').dataset.dirty='true';});}
const txtSave=document.createElement('button');txtSave.type='button';txtSave.id='saveTxtSettings';txtSave.className='btn btn-primary';txtSave.textContent='儲存 TXT 設定';txtSave.onclick=()=>$('settingsForm').requestSubmit();txtOptions.append(txtSave);document.querySelector('#settings .obs-panel').append(txtOptions);
const settingsLink=document.createElement('p');settingsLink.className='creator-help';settingsLink.textContent='字型、字色與背景請到「OBS 外觀與輸出 → 調整外觀」。OBS 間距與名稱長度也在工作室設定；純文字選項請到「OBS 外觀與輸出 → 純文字輸出（TXT）」。';appearance.querySelector('#settingsForm').before(settingsLink);
document.querySelector('#settings .panel-heading h2').textContent='選擇要放進 OBS 的榜單';document.querySelector('#events h2').textContent='支持紀錄';document.querySelector('#records .panel-heading p').textContent='先確認實況主，再加入要統計的直播；其他頻道的支持不會混進來。';document.querySelector('.obs-steps li:last-child').textContent='建議先用寬 700、高 700，依名次與字級調整；三種榜單皆可獨立套用外觀。';$('publishObs').title='立即核對背景輸出；OBS 平常每兩秒自行更新。這不補抓歷史，也不更換 OBS 網址。';
// Three editing tabs reuse the existing controls and handlers.
const sections=[...$('themeForm').children].filter(e=>e.tagName==='FIELDSET');
const tabBar=document.createElement('div');tabBar.className='board-editor-tabs';tabBar.setAttribute('role','tablist');tabBar.setAttribute('aria-label','榜單設定');
const editorPanels={};
for(const [id,label]of [['content','內容'],['text','文字與名次'],['layout','背景與版面']]){const button=document.createElement('button');button.type='button';button.id='editor-tab-'+id;button.setAttribute('role','tab');button.setAttribute('aria-controls','editor-panel-'+id);button.textContent=label;button.onclick=()=>selectEditorTab(id);tabBar.append(button);const panel=document.createElement('div');panel.id='editor-panel-'+id;panel.setAttribute('role','tabpanel');panel.setAttribute('aria-labelledby',button.id);panel.className='board-editor-panel';editorPanels[id]=panel;}
$('themeForm').before(tabBar);
function selectEditorTab(id){for(const [key,panel]of Object.entries(editorPanels)){panel.hidden=key!==id;const button=$('editor-tab-'+key);button.setAttribute('aria-selected',String(key===id));button.tabIndex=key===id?0:-1;}studio.querySelector('.creator-inspector').scrollTop=0;}
tabBar.onkeydown=e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;const buttons=[...tabBar.children],i=buttons.indexOf(document.activeElement);if(i<0)return;e.preventDefault();const next=e.key==='Home'?0:e.key==='End'?2:(i+(e.key==='ArrowRight'?1:2))%3;buttons[next].click();buttons[next].focus();};
editorPanels.content.append($('themeTitle').closest('label'));
for(const p of RankTheme.periods){const field=$('themeTitle_'+p).closest('label');field.querySelector('span').textContent='榜單名稱';editorPanels.content.append(field);}
$('themeTitles').remove();
editorPanels.content.append($('studioTop').closest('label'),$('themeMaxNameLength').closest('label'),$('nameAdvanced'));
const rankFields=document.createElement('fieldset');rankFields.append($('themeMedals').closest('label'),$('themeRankIcons'));
editorPanels.text.append(sections[1],rankFields);
editorPanels.layout.append(sections[0],sections[3],sections[2]);
$('themeForm').append(...Object.values(editorPanels));
for(const legend of $('themeForm').querySelectorAll('legend'))legend.classList.add('visually-hidden');
studio.querySelector('.studio-toolbar').remove();
const delivery=studio.querySelector('.creator-delivery');studio.append(delivery);delivery.querySelector('strong').textContent='只更新目前這張榜';delivery.querySelector('p').replaceWith($('studioSavedState'));$('applyTheme').textContent='儲存並更新這張榜';
const copyCurrent=document.createElement('button');copyCurrent.type='button';copyCurrent.className='btn btn-outline-secondary';copyCurrent.id='copyCurrentBoardUrl';copyCurrent.textContent='複製 OBS 網址';copyCurrent.onclick=()=>copyBoardUrl(activeKind,activePeriod);
const copyAppearance=document.createElement('button');copyAppearance.type='button';copyAppearance.className='btn btn-outline-secondary';copyAppearance.id='copyAppearance';copyAppearance.textContent='複製外觀到其他榜';
delivery.append(copyCurrent,copyAppearance);studio.querySelector('.creator-inspector > details').append($('themeCss'));delivery.after($('themeNotice'));
studio.querySelector('.panel-heading .creator-eyebrow').remove();
$('studioBack').textContent='← 返回九張榜單';
selectEditorTab('content');
const copyDialog=document.createElement('dialog');copyDialog.className='board-copy-dialog';copyDialog.innerHTML='<h2>複製外觀到其他榜</h2><p id="copySource"></p><p class="creator-help">只複製已儲存的字型、顏色、背景、圖示及版面；各榜名稱與顯示名次保留。複製後不會持續連動。</p><div id="copyTargets"></div><p id="copySummary" role="status"></p><div class="board-actions"><button type="button" id="cancelCopyAppearance" class="btn btn-outline-secondary">取消</button><button type="button" id="confirmCopyAppearance" class="btn btn-primary" disabled>確認覆蓋外觀</button></div><p id="copyError" role="status"></p>';document.body.append(copyDialog);let copySource=null;
$('cancelCopyAppearance').onclick=()=>copyDialog.close();
copyAppearance.onclick=()=>{if(dirty){showToast('請先儲存目前草稿，再複製外觀。');return;}if(!RankTheme.select(StyleStore.styles,activeKind,activePeriod).enabled){showToast('請先儲存這張榜的外觀。');return;}copySource={kind:activeKind,period:activePeriod,revision:StyleStore.remoteRevision};$('copySource').textContent='來源：'+boardLabel(activeKind,activePeriod)+' · '+boardTitle(activeKind,activePeriod);$('copyTargets').replaceChildren();$('copyError').textContent='';for(const kind of RankTheme.kinds)for(const period of RankTheme.periods){if(kind===activeKind&&period===activePeriod)continue;const label=document.createElement('label');label.className='creator-check';const check=document.createElement('input');check.type='checkbox';check.value=kind+':'+period;const span=document.createElement('span');span.textContent=boardLabel(kind,period)+' · '+boardTitle(kind,period);label.append(check,span);$('copyTargets').append(label);}updateCopySummary();copyDialog.showModal();};
function selectedCopies(){return [...$('copyTargets').querySelectorAll('input:checked')].map(e=>e.value);}
function updateCopySummary(){const targets=selectedCopies();$('copySummary').textContent=targets.length?'將覆蓋：'+targets.map(k=>boardLabel(...k.split(':'))).join('、'):'請選擇要套用的榜单';$('confirmCopyAppearance').disabled=!targets.length;}
$('copyTargets').onchange=updateCopySummary;
$('confirmCopyAppearance').onclick=async()=>{const button=$('confirmCopyAppearance');button.disabled=true;try{await StyleStore.copy(copySource.kind,copySource.period,selectedCopies(),copySource.revision);copyDialog.close();draftStyleRevision=StyleStore.remoteRevision;refreshBoards();showToast('外觀已複製，榜名與名次保留；各榜仍獨立。');}catch(e){$('copyError').textContent=e.message;}finally{button.disabled=!selectedCopies().length;}};
// Keep risk/status messages visible; collapse only static explanatory paragraphs.
function foldExplanation(node,title){if(!node)return;const box=document.createElement('details'),summary=document.createElement('summary');box.className='creator-help compact-help';summary.textContent=title;node.before(box);box.append(summary,node);}
for(const [text,title]of [['靠右排列會保留','排列方式說明'],['位置 0% 對齊','背景位置說明']]){foldExplanation([...studio.querySelectorAll('p')].find(p=>p.textContent.startsWith(text)),title);}
document.querySelector('#events .panel-heading p').textContent='選「詳情」查看留言與未計入原因。';
document.querySelector('#ranking .panel-heading p').textContent='選擇期間與榜單，查看統計結果。';
document.querySelector('#settings .panel-heading p').textContent='每張榜獨立設定；從卡片複製網址，不會切錯期間。';
document.querySelector('#records .panel-heading p').textContent='鎖定頻道，加入要統計的直播。';
settingsLink.textContent='字型、間距與背景：OBS 外觀與輸出 → 調整外觀。';
appearance.querySelector('.panel-heading p').textContent='設定只保存在本機。';
sidebarNote.textContent='紀錄只存本機';
const rawRender=render;render=function(connected=true){rawRender(connected);const heading=document.createElement('div');heading.className='panel-heading creator-overview-heading';heading.innerHTML='<div><p class="creator-eyebrow">YOUR STREAM, AT A GLANCE</p><h2>直播總覽</h2></div>';$('overview').prepend(heading);refreshBoards();if(!studio.hidden)draw();};
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
StyleStore.ready.then(()=>{$('applyTheme').disabled=false;}).catch(e=>{const warning=document.createElement('p');warning.className='alert alert-warning';warning.textContent='外觀資料讀取失敗，已保留原始紀錄與其他設定：'+e.message;document.querySelector('.obs-panel').prepend(warning);});

// Fixed workspace action bars: reserve their measured height, including wrapped buttons.
const dockMain=document.querySelector('main'),dockRoot=document.documentElement,dockObserved=new WeakSet();let dockFrame=0;
const dockResize=new ResizeObserver(scheduleDock);
function scheduleDock(){if(!dockFrame)dockFrame=requestAnimationFrame(syncDock);}
function syncDock(){dockFrame=0;const bounds=dockMain.getBoundingClientRect();dockRoot.style.setProperty('--dock-left',Math.max(0,bounds.left)+'px');dockRoot.style.setProperty('--dock-width',Math.min(innerWidth,bounds.width)+'px');let height=0;
for(const bar of document.querySelectorAll('#studio .creator-delivery,#historyConfirmArea')){if(!dockObserved.has(bar)){dockObserved.add(bar);dockResize.observe(bar);}if(bar.getClientRects().length)height=Math.max(height,bar.getBoundingClientRect().height);}
dockRoot.style.setProperty('--dock-height',height+'px');}
dockResize.observe(dockMain);new MutationObserver(scheduleDock).observe(dockMain,{subtree:true,childList:true,attributes:true,attributeFilter:['hidden','class','open']});window.addEventListener('resize',scheduleDock);scheduleDock();

render(connectionMode!=='none');switchPage('overview');
})();
