'use strict';
(function(root){
 function reason(error){const message=String(error?.message||'');return /[\u3400-\u9fff]/.test(message)?message:/network|fetch/i.test(message)?'瀏覽器未能載入本機字型資料':'此環境無法解析字型';}
 const safe=v=>typeof v==='string'&&/^[\p{L}\p{N} _.,-]{1,100}$/u.test(v);
 let catalog=[],target=null,limit=100;const assets=new Map(),assetPending=new Map();const faces=createRankFaceCache({add:face=>document.fonts.add(face),remove:face=>document.fonts.delete(face)});let nextFace=0;
 function sourcesFor(name){const f=catalog.find(f=>f.family===name||f.label===name||f.aliases.includes(name));return f?[...new Set([f.label,...f.aliases,f.family])]:[];}
 async function ensureAsset(name){const f=catalog.find(f=>f.family===name);if(!f?.fileId)return '';if(assets.has(name))return assets.get(name);if(!assetPending.has(name))assetPending.set(name,LocalRuntime.request('/fonts/'+f.fileId).then(v=>{if(typeof v.data!=='string'||v.data.length>45000000||!/^data:font\/(ttf|otf);base64,[A-Za-z0-9+/]+={0,2}$/.test(v.data))throw Error('本機字型資料不正確');assets.set(name,v.data);while([...assets.values()].reduce((n,v)=>n+v.length,0)>48000000)assets.delete(assets.keys().next().value);return v.data;}).finally(()=>assetPending.delete(name)));return assetPending.get(name);}
 async function loadFace(name,hints,data){
   const sources=Array.isArray(hints)&&hints.length?hints:sourcesFor(name);
   // A compact digest avoids retaining a second 32 MB data URL as a Map key.
   const digest=data?Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(data))),v=>v.toString(16).padStart(2,'0')).join(''):'';
   const key=JSON.stringify([name,sources,digest]);
   return faces.get(key,name,async()=>{
     const family='RankFontChoice'+(++nextFace);let bytes=data?data.length*3/4:0,face;
     try{face=await new FontFace(family,data?'url('+JSON.stringify(data)+')':(sources.length?sources:[name]).map(v=>'local('+JSON.stringify(v)+')').join(',')).load();}
     catch(error){const recovered=await ensureAsset(name);if(!recovered)throw error;bytes=recovered.length*3/4;face=await new FontFace(family,'url('+JSON.stringify(recovered)+')').load();}
     return {face,bytes};
   });
 }

 const dialog=document.createElement('dialog');dialog.className='creator-font-dialog';
 dialog.innerHTML='<div class="inspector-heading"><h2>尋找字型</h2><button type="button" class="btn btn-outline-secondary" data-close>關閉</button></div><label class="field">搜尋名稱或別名<input class="form-control" type="search" placeholder="例如：正黑、JhengHei、Arial" aria-label="搜尋字型"></label><p class="creator-help" data-count role="status"></p><p class="creator-help">樣張包含中／日／英文字。字型未收錄的字形可能由替代字型顯示；字型內的空白字形無法自動補回。</p><div class="font-results"></div><button type="button" class="btn btn-outline-secondary" data-more>顯示更多字型</button>';
 document.body.append(dialog);
 const search=dialog.querySelector('input'),results=dialog.querySelector('.font-results');
 const observer=new IntersectionObserver(entries=>{for(const e of entries)if(e.isIntersecting){e.target._loadSample?.();}},{root:dialog.querySelector('.font-results'),rootMargin:'100px'});
 function render(){observer.disconnect();const term=search.value.trim().toLocaleLowerCase(),matches=catalog.filter(f=>[f.family,f.label,...f.aliases].join(' ').toLocaleLowerCase().includes(term));results.replaceChildren();for(const f of matches.slice(0,limit)){const b=document.createElement('button');b.type='button';b.className='font-choice';const name=document.createElement('strong'),alias=document.createElement('small'),sample=document.createElement('span');name.textContent=f.label;const aliases=[f.family,...f.aliases].filter((v,i,a)=>v!==f.label&&a.indexOf(v)===i);alias.textContent=f.family;alias.title=aliases.join(' · ');sample.className='font-choice-sample';sample.textContent='支持你的每一刻 Aa 123';sample.textContent='正在載入字型…';sample._loadSample=()=>loadFace(f.family).then(face=>{sample.style.fontFamily=JSON.stringify(face)+', "Microsoft JhengHei", sans-serif';sample.textContent='支持你的每一刻 あいう アイウ Aa 123';sample.dataset.loaded='true';}).catch(error=>{sample.textContent=reason(error)+' · 仍可選用';sample.dataset.loaded='false';});b.append(name,alias,sample);b.onclick=()=>{const chosen=target;if(chosen){chosen.value=f.family;chosen.dispatchEvent(new Event('input',{bubbles:true}));}dialog.close();chosen?.focus();loadFace(f.family).catch(()=>{});};const card=document.createElement('div');card.className='font-option';card.append(b);if(aliases.length>1){const detail=document.createElement('details'),summary=document.createElement('summary'),text=document.createElement('p');detail.className='creator-help';summary.textContent='字型別名';text.textContent=aliases.join(' · ');detail.append(summary,text);card.append(detail);}results.append(card);observer.observe(sample);}dialog.querySelector('[data-more]').hidden=matches.length<=limit;dialog.querySelector('[data-count]').textContent=catalog.length?(matches.length?'找到 '+matches.length+' 種'+(matches.length>limit?'，目前顯示 '+limit+' 種，可按下方載入更多。':''):'找不到字型，可改用別名搜尋或匯入字型檔。'):'請先按「讀取本機字型」，也可以直接輸入字型名稱。';}
 dialog.addEventListener('close',()=>{observer.disconnect();faces.prune();});search.oninput=()=>{limit=100;render();};dialog.querySelector('[data-more]').onclick=()=>{limit+=100;render();};dialog.querySelector('[data-close]').onclick=()=>dialog.close();
 function setCatalog(values){const unique=new Map();for(const value of values){const f=typeof value==='string'?{family:value,label:value,aliases:[]}:value;if(!f||!safe(f.family))continue;unique.set(f.family,{fileId:/^[a-f0-9]{64}$/.test(f.fileId||'')?f.fileId:'',family:f.family,label:safe(f.label)?f.label:f.family,aliases:Array.isArray(f.aliases)?f.aliases.filter(safe):[]});}catalog=[...unique.values()].sort((a,b)=>a.label.localeCompare(b.label,'zh-Hant'));const list=document.getElementById('installedFontNames');list.replaceChildren();for(const f of catalog){const option=document.createElement('option');option.value=f.family;option.label=[f.label,...f.aliases].join(' / ');list.append(option);}render();return catalog.length;}
 function attach(input){const button=document.createElement('button');button.type='button';button.className='btn btn-outline-secondary font-picker-button';button.textContent='搜尋與試看';button.setAttribute('aria-label','搜尋'+(input.getAttribute('aria-label')||'整體字型'));input.after(button);button.onclick=()=>{target=input;search.value='';limit=100;render();dialog.showModal();search.focus();};}
 root.RankFontPicker={attach,setCatalog,sourcesFor,loadFace,pin:names=>faces.pin(names),cacheStats:()=>faces.stats(),assetFor:name=>assets.get(name)||''};
})(globalThis);
