'use strict';
(function(){
 if(new URLSearchParams(location.search).has('obs'))return;
 const root=document.getElementById('sessionManager');let tab='joined',busy=false,lastKey='',active='',page=0,monthInitialized=false;
 root.innerHTML='<h3>直播場次管理</h3><div class="session-tabs" role="tablist" aria-label="場次統計狀態"><button id="sessionsJoined" type="button" role="tab" class="btn">已加入統計</button><button id="sessionsOther" type="button" role="tab" class="btn">未加入統計</button></div><label class="field"><span>搜尋標題或影片 ID</span><input id="sessionSearch" class="form-control" type="search"></label><label class="creator-check"><input id="sessionLookupConsent" type="checkbox">同意向 YouTube 查詢影片公開標題與頻道</label><p class="creator-help">查詢會傳送公開影片網址與連線 IP，不傳支持紀錄；結果只存本機。</p><p id="sessionManagerNotice" role="status"></p><div id="sessionRows" role="tabpanel"></div>';
 const get=id=>document.getElementById(id),tell=value=>get('sessionManagerNotice').textContent=value;
 const filters=document.createElement('div');filters.className='session-filters';
 filters.innerHTML='<label>紀錄年份<select id="sessionYear" class="form-select"><option value="">全部年份</option></select></label><label>紀錄月份<select id="sessionMonth" class="form-select"><option value="">全部月份</option></select></label><label id="sessionStatusLabel" hidden>未加入狀態<select id="sessionStatus" class="form-select"><option value="">全部未加入</option><option>待確認</option><option>已略過</option><option>已移出</option><option>其他頻道</option></select></label><button id="sessionAllMonths" type="button" class="btn btn-outline-secondary">搜尋全部月份</button>';
 get('sessionSearch').parentElement.after(filters);
 const pagination=document.createElement('div');pagination.className='session-pagination';pagination.innerHTML='<button id="sessionPrev" type="button" class="btn btn-outline-secondary">上一頁</button><span id="sessionPageInfo" role="status"></span><button id="sessionNext" type="button" class="btn btn-outline-secondary">下一頁</button>';
 const detail=document.createElement('section');detail.id='sessionDetail';detail.className='session-detail';detail.setAttribute('aria-label','選取場次的資訊與操作');detail.hidden=true;const browser=document.createElement('div');browser.className='session-browser';get('sessionRows').before(browser);browser.append(get('sessionRows'),detail);browser.after(pagination);
 for(let i=1;i<=12;i++){const option=document.createElement('option');option.value=String(i).padStart(2,'0');option.textContent=i+' 月';get('sessionMonth').append(option);}
 const recordMonth=row=>RecordPolicy.dateParts(row.date)?.month||'';
 function catalog(){const lock=currentChannelLock(),rows=new Map();const add=(id,title='',date='')=>{if(!ChannelLock.validLive(id))return;const row=rows.get(id)||{id,title:'',date:''};if(!row.title&&title)row.title=title;if(RecordPolicy.validTimestamp(date)&&(!row.date||Date.parse(date)<Date.parse(row.date)))row.date=date;rows.set(id,row);};
  for(const event of state.events||[])if(event.service==='youtube')add(event.liveId,event.streamTitle,event.timestamp);
  for(const source of state.services||[])add(source.resolvedLiveId||ChannelLock.parseLive(source.url),source.streamTitle);
  for(const key of ['bindings','removedLives','dismissedLives','videoCatalog'])for(const id of Object.keys(lock[key]||{}))add(id);
  return [...rows.values()].map(row=>{const meta=lock.videoCatalog[row.id],joined=ChannelLock.allows(lock,row.id),foreign=lock.bindings[row.id]?.channelId&&lock.bindings[row.id].channelId!==lock.channelId||meta?.source==='youtube-public-metadata'&&meta.channelId!==lock.channelId;return {...row,title:row.title||meta?.title||'尚未取得影片標題',meta,joined,foreign,status:joined?'已加入統計':foreign?'其他頻道':ChannelLock.removed(lock,row.id)?'已移出':lock.dismissedLives[row.id]?.channelId===lock.channelId?'已略過':'待確認'};});
 }
 function refresh(force=false){const rows=catalog(),key=JSON.stringify([rows,currentChannelLock().channelId,tab,get('sessionSearch').value,get('sessionYear').value,get('sessionMonth').value,get('sessionStatus').value,busy,page,active]);if(!force&&key===lastKey)return;lastKey=key;
  const years=[...new Set(rows.map(r=>recordMonth(r).slice(0,4)).filter(Boolean))].sort().reverse(),year=get('sessionYear'),previousYear=year.value;year.replaceChildren();for(const [value,label]of [['','全部年份'],...years.map(y=>[y,y+' 年']),['unknown','日期不明']]){const o=document.createElement('option');o.value=value;o.textContent=label;year.append(o);}year.value=years.includes(previousYear)||previousYear==='unknown'?previousYear:'';
  if(!monthInitialized&&rows.length){const latest=rows.filter(r=>r.joined===(tab==='joined')).map(recordMonth).filter(Boolean).sort().at(-1);if(latest){year.value=latest.slice(0,4);get('sessionMonth').value=latest.slice(5);}monthInitialized=true;}
  get('sessionMonth').disabled=year.value==='unknown';get('sessionStatusLabel').hidden=tab==='joined';
  get('sessionsJoined').textContent='已加入統計（'+rows.filter(r=>r.joined).length+'）';get('sessionsOther').textContent='未加入統計（'+rows.filter(r=>!r.joined).length+'）';for(const [id,value]of [['sessionsJoined','joined'],['sessionsOther','other']]){get(id).setAttribute('aria-selected',String(tab===value));get(id).setAttribute('aria-controls','sessionRows');}
  get('sessionRows').setAttribute('aria-labelledby',tab==='joined'?'sessionsJoined':'sessionsOther');const search=get('sessionSearch').value.trim().toLowerCase(),filtered=rows.filter(r=>{const month=recordMonth(r);return r.joined===(tab==='joined')&&(r.title+' '+r.id).toLowerCase().includes(search)&&(tab==='joined'||!get('sessionStatus').value||r.status===get('sessionStatus').value)&&(year.value==='unknown'?!month:(!year.value||month.startsWith(year.value))&&(!get('sessionMonth').value||month.slice(5)===get('sessionMonth').value));}).sort((a,b)=>b.date.localeCompare(a.date)||a.id.localeCompare(b.id));get('sessionRows').replaceChildren();detail.replaceChildren();detail.hidden=true;
  const pages=Math.max(1,Math.ceil(filtered.length/20));page=Math.min(page,pages-1);get('sessionPrev').disabled=page===0;get('sessionNext').disabled=page>=pages-1;get('sessionPageInfo').textContent=(page+1)+' / '+pages+' 頁 · '+filtered.length+' 場（每頁 20 場）';
  if(!filtered.length){get('sessionRows').textContent='沒有符合的場次；可切換月份或選「搜尋全部月份」。';return;}
  for(const row of filtered.slice(page*20,page*20+20)){const card=document.createElement('article');card.className='session-row';card.dataset.sessionId=row.id;
   const heading=document.createElement('div'),title=document.createElement('strong'),sub=document.createElement('p');title.textContent=row.title;sub.className='creator-help';sub.textContent=row.status+' · '+(row.date?new Date(row.date).toLocaleDateString('zh-TW',{timeZone:'Asia/Taipei'})+' · ':'')+row.id;heading.append(title,sub);
   sub.textContent=row.status+' · 紀錄日期：'+(RecordPolicy.dateParts(row.date)?.day||'不明')+(row.title==='尚未取得影片標題'?' · '+row.id:'');const select=document.createElement('button');select.type='button';select.className='session-select';select.dataset.sessionView=row.id;select.setAttribute('aria-pressed',String(active===row.id));select.setAttribute('aria-controls','sessionDetail');select.append(heading);select.onclick=()=>{active=row.id;refresh(true);get('sessionRows').querySelector('[data-session-view="'+row.id+'"]')?.focus();};card.append(select);get('sessionRows').append(card);if(active!==row.id)continue;
   detail.hidden=false;const fullTitle=document.createElement('h4');fullTitle.textContent=row.title;const identifier=document.createElement('p');identifier.className='creator-help';identifier.textContent='影片 ID：'+row.id+' · 最早紀錄日期：'+(RecordPolicy.dateParts(row.date)?.day||'不明')+'（不是開台時間）';detail.append(fullTitle,identifier);
   const actions=document.createElement('div');actions.className='session-row-actions';const view=document.createElement('a');view.textContent='開啟影片';view.href='https://www.youtube.com/watch?v='+row.id;view.target='_blank';view.rel='noopener noreferrer';view.referrerPolicy='no-referrer';actions.append(view);
   const query=document.createElement('button');query.type='button';query.className='btn btn-outline-secondary';query.textContent='查詢資訊';query.disabled=busy;query.onclick=()=>lookup(row);actions.append(query);
   const change=document.createElement('button');change.type='button';change.className='btn '+(row.joined?'btn-outline-danger':'btn-outline-primary');change.dataset.sessionOperation=row.joined?'remove':'join';change.textContent=row.joined?'移出統計':row.status==='已移出'?'重新加入':'確認加入';change.disabled=busy||!currentChannelLock().channelId||!row.joined&&!!row.foreign;change.onclick=()=>membership(row);actions.append(change);
   const info=document.createElement('p');info.className='creator-help';info.textContent=row.meta?(row.meta.source==='youtube-public-metadata'?'YouTube 目前公開資料':'OneComme 本機資訊')+' · '+(row.meta.channelName||'未提供頻道名稱')+' · '+(row.meta.channelId||'尚未查證頻道'):'目前只依本機紀錄與歸屬設定顯示；可主動查詢公開資訊。';detail.append(info,actions);
  }
 }
 async function membership(row){if(busy)return;const channelId=currentChannelLock().channelId;if(!channelId)return;const operation=row.joined?'remove':'join';if(!confirm((row.joined?'移出統計：':'確認加入目前鎖定頻道：')+row.title+'\n影片 ID：'+row.id+'\n'+(row.joined?'不再計入各期排行榜，原始紀錄保留。可隨時重新加入。':'請自行核對頻道歸屬。使用既有紀錄重新計算，不重複新增事件；已清空與測試紀錄仍不計入。')))return;
  busy=true;refresh(true);try{await LocalRuntime.request('/api','POST',{action:'sessionMembership',channelId,liveId:row.id,operation,confirmed:true});await load();tell(row.joined?'已移出統計，紀錄保留；可在「未加入統計」重新加入。':'已加入統計；既有紀錄重新計算，不重複新增。');}catch(e){tell('操作未完成：'+e.message);}finally{busy=false;refresh(true);}
 }
 async function lookup(row){if(busy)return;if(!get('sessionLookupConsent').checked){tell('請先勾選同意查詢公開影片資訊。');return;}busy=true;refresh(true);tell('正在查詢，不會自動加入統計…');try{await LocalRuntime.request('/api','POST',{action:'sessionLookup',channelId:currentChannelLock().channelId,liveId:row.id,consent:true});await load();tell('影片資訊已存於本機；查詢不會變更統計歸屬。');}catch(e){tell('查詢失敗：'+e.message+'；原紀錄保留。');}finally{busy=false;refresh(true);}}
 get('sessionsJoined').onclick=()=>{tab='joined';page=0;refresh(true);};get('sessionsOther').onclick=()=>{tab='other';page=0;refresh(true);};get('sessionSearch').oninput=()=>{page=0;refresh(true);};
 for(const id of ['sessionYear','sessionMonth','sessionStatus'])get(id).onchange=()=>{monthInitialized=true;page=0;active='';refresh(true);};
 get('sessionAllMonths').onclick=()=>{monthInitialized=true;get('sessionYear').value=get('sessionMonth').value='';page=0;refresh(true);};get('sessionPrev').onclick=()=>{page--;active='';refresh(true);};get('sessionNext').onclick=()=>{page++;active='';refresh(true);};
 root.querySelector('.session-tabs').onkeydown=e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();const id=e.key==='Home'?'sessionsJoined':e.key==='End'?'sessionsOther':tab==='joined'?'sessionsOther':'sessionsJoined';get(id).click();get(id).focus();};
 new MutationObserver(()=>refresh()).observe(document.getElementById('eventRows'),{childList:true});refresh();
})();
