'use strict';
(function(){
 const box=document.createElement('details');box.className='advanced-block';box.id='storageManagement';
 box.innerHTML='<summary>資料空間與本機備份</summary><p>紀錄按台北月份分檔，外觀資源獨立保存。所有月份仍會納入歷史榜，不會因分檔而消失。</p><p id="storageUsage" role="status">展開後讀取空間用量。</p><div class="action-row"><button type="button" class="btn btn-outline-primary" id="storageRefresh">重新整理用量</button><button type="button" class="btn btn-outline-primary" id="storageBackup">建立本機壓縮備份</button><button type="button" class="btn btn-outline-secondary" id="storageCleanup">整理舊備份（保留最新 5 份）</button></div><p id="storageActionNotice" role="status"></p><p class="creator-help">只整理此區建立的手動／會員修復備份；不刪除任何月份紀錄，也不刪升級與移入前備份。清空統計不會釋放歷史紀錄空間。備份含個人資料與金鑰，請勿公開分享。</p><p class="creator-help">需要下載到其他位置？使用上方既有的「完整 JSON 備份」，不需重複匯出。</p>';
 document.getElementById('exports').append(box);const status=box.querySelector('#storageUsage'),notice=box.querySelector('#storageActionNotice'),buttons=[...box.querySelectorAll('button')];
 function size(n){return n<1024?n+' B':n<1048576?(n/1024).toFixed(1)+' KB':(n/1048576).toFixed(1)+' MB';}
 async function run(action,confirmed=false){buttons.forEach(b=>b.disabled=true);try{if(connectionMode!=='plugin')throw Error('請先啟用背景插件');const result=await LocalRuntime.request('/api','POST',{action,confirmed});if(!result.storage)throw Error('請在 OneComme 重新載入新版擴充功能後再試');const s=result.storage;status.textContent='總用量 '+size(s.totalBytes)+' · 紀錄 '+size(s.categories.records)+' · 外觀 '+size(s.categories.appearance)+' · 備份 '+size(s.categories.backups)+' · 輸出 '+size(s.categories.outputs)+'。共 '+s.months.length+' 個月份／待確認日期分檔。資料位置：'+s.dataPath;notice.textContent=result.cleanup?'已移除 '+result.cleanup.removed+' 份舊備份，釋放 '+size(result.cleanup.bytes)+'；歷史紀錄未刪除。':result.backup?(result.backup.reused?'內容相同的本機備份已存在，沒有重複占用空間。':'本機壓縮備份已建立（含所有紀錄、設定、外觀與金鑰）。'):s.maintenanceWarning||'用量已更新。';}catch(e){notice.textContent=e.message;}finally{buttons.forEach(b=>b.disabled=false);}}
 box.addEventListener('toggle',()=>{if(box.open)run('storageInfo');});box.querySelector('#storageRefresh').onclick=()=>run('storageInfo');box.querySelector('#storageBackup').onclick=()=>run('storageBackup');box.querySelector('#storageCleanup').onclick=()=>{if(confirm('只保留最新 5 份手動／會員修復壓縮備份，其餘將永久刪除。原始紀錄、升級與移入備份不受影響。是否繼續？'))run('storageCleanup',true);};
})();
