(function(root){'use strict';
let styles={},db=null,error='',ready=false,revision=0,saving=false,background=false,remoteRevision='';
const opened=new Promise((resolve,reject)=>{if(!root.indexedDB)return reject(Error('瀏覽器不支援外觀儲存'));const request=indexedDB.open('yt-rank-show-appearance-v1',1);request.onupgradeneeded=()=>request.result.createObjectStore('settings');request.onerror=()=>reject(request.error);request.onblocked=()=>reject(Error('外觀資料庫被其他分頁阻擋，請關閉重複管理頁'));request.onsuccess=()=>{db=request.result;db.onversionchange=()=>db.close();const tx=db.transaction('settings'),read=tx.objectStore('settings').get('styles');read.onsuccess=()=>{try{styles=RankTheme.normalizeMap(read.result||{});ready=true;resolve(styles)}catch(e){reject(e)}};read.onerror=()=>reject(read.error);};}).catch(e=>{error=e.message||'外觀讀取失敗';throw e;});
// Keep failure visible without an unhandled rejection during page initialization.
opened.catch(()=>{});
async function save(kind,value,expectedRevision=remoteRevision,period='',inherit=false){if(!RankTheme.kinds.includes(kind))throw Error('榜單類型不正確');await opened;if(saving)throw Error('外觀正在保存，請稍候');const next=RankTheme.saveBoard(styles,kind,period,value);saving=true;try{if(background){const response=await root.LocalRuntime.request('/api','POST',{action:'styles',kind,value,expectedRevision,period});styles=RankTheme.normalizeMap(response.styles);remoteRevision=response.styleRevision;revision++;root.dispatchEvent(new Event('rank-style-saved'));return RankTheme.select(styles,kind,period);}await new Promise((resolve,reject)=>{const tx=db.transaction('settings','readwrite');tx.objectStore('settings').put(next,'styles');tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error||Error('外觀保存失敗'));tx.onabort=()=>reject(tx.error||Error('外觀保存被中止'));});styles=next;revision++;root.dispatchEvent(new Event('rank-style-saved'));return RankTheme.select(styles,kind,period);}finally{saving=false;}}
async function copy(kind,period,targets,expectedRevision=remoteRevision){await opened;if(saving)throw Error('外觀正在保存');if(!background)throw Error('複製外觀需要背景插件啟用');saving=true;try{const response=await root.LocalRuntime.request('/api','POST',{action:'copyStyles',kind,period,targets,expectedRevision,confirmed:true});styles=RankTheme.normalizeMap(response.styles);remoteRevision=response.styleRevision;revision++;root.dispatchEvent(new Event('rank-style-saved'));}finally{saving=false;}}
root.StyleStore={ready:opened,save,copy,async useBackground(value,version){await opened;styles=RankTheme.normalizeMap(value);background=true;remoteRevision=version;revision++;},get remoteRevision(){return remoteRevision;},get styles(){return styles;},get loaded(){return ready;},get error(){return error;},get revision(){return revision;}};
})(globalThis);
