'use strict';
(function(){
 const box=document.createElement('section');box.className='ui-region';box.id='softwareUpdates';box.innerHTML='<h3>軟體更新</h3><p id="updateStatus" role="status">正在讀取本機版本。</p><label><input id="updateAutomatic" type="checkbox">自動檢查正式新版（連線 GitHub）</label><p class="creator-help">只查版本、不自動安裝；GitHub 會收到連線 IP。不傳送頻道、支持紀錄或 OBS 金鑰。</p><div class="action-row"><button id="updateCheck" class="btn btn-outline-primary" type="button">檢查更新（GitHub）</button><button id="updateDownload" class="btn btn-outline-primary" type="button" disabled>下載更新</button><button id="updateInstall" class="btn btn-primary" type="button" disabled>開啟更新視窗</button></div><details id="updateChanges" hidden><summary>本次更新內容</summary><pre id="updateNotes" style="white-space:pre-wrap"></pre></details>';
 document.getElementById('appearance').append(box);const $=id=>box.querySelector('#'+id);let active=false;
 function render(s){$('updateAutomatic').checked=s.automatic;$('updateCheck').disabled=s.busy||s.phase==='waiting';$('updateDownload').disabled=s.busy||!s.available||s.ready||s.phase==='waiting';$('updateInstall').disabled=s.busy||!s.ready;$('updateChanges').hidden=!s.available;$('updateNotes').textContent=s.available?.notes||'';$('updateStatus').textContent='目前 v'+s.current+' · '+(s.error||({checking:'正在檢查新版…',downloading:'正在下載與驗證…',ready:'更新包已備妥；開啟更新視窗後，請自行關閉 OneComme。',waiting:'更新視窗已開啟；請關閉 OneComme 後繼續。'}[s.phase])||(s.available?'可更新至 v'+s.available.version:s.lastChecked?'沒有較新的正式發布版本。':'尚未檢查新版。'));}
 async function run(action,extra={}){if(active)return;active=true;try{for(const b of box.querySelectorAll('button'))b.disabled=true;const s=await LocalRuntime.request('/updates',action?'POST':'GET',action?{action,...extra}:undefined);render(s);}catch(e){$('updateStatus').textContent=e.message;$('updateCheck').disabled=false;}finally{active=false;}}
 $('updateCheck').onclick=()=>run('check',{consent:true});$('updateDownload').onclick=()=>run('download',{consent:true});$('updateInstall').onclick=()=>{if(confirm('開啟獨立更新視窗後，請自行關閉 OneComme。關閉後會備份並安裝，期間請勿重新開啟 OneComme。是否繼續？'))run('install',{confirmed:true});};$('updateAutomatic').onchange=()=>run('preferences',{automatic:$('updateAutomatic').checked});
 run();setInterval(()=>{if(!document.hidden)run();},60000);
})();
