'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),os=require('node:os');
const {createRuntime}=require('../src/runtime'),{createResolverServer}=require('../scripts/resolver-server'),Theme=require('../style-theme'),Lock=require('../channel-lock');
const A='UC'+'a'.repeat(22),B='UC'+'b'.repeat(22),V='live0000001',W='live0000002';
const service=(id,channel)=>({id,url:'https://www.youtube.com/channel/'+channel,enabled:true});
const meta=(source,live,extra={})=>({type:'youtube',service:source,data:{url:'https://www.youtube.com/watch?v='+live,title:'Stream',...extra}});
const comment=(live,id)=>({service:'youtube',data:{liveId:live,id,userId:id,name:id,type:'superchat',price:30,unit:'TWD',timestamp:new Date().toISOString()}});
async function setup(initial={}){const dir=await fs.mkdtemp(path.join(os.tmpdir(),'yt-auto-'));return {dir,r:await createRuntime({dir,store:{store:{channelLock:{channelId:A}}}},initial)};}
test('固定頻道 metadata 自動確認；既有待確認支持入榜；跨场跟隨且重啟保留',async()=>{const s=service('one',A),{r,dir}=await setup({services:[s]});try{await r.subscribe('comments',[comment(V,'one')]);assert.doesNotMatch(r.snapshot().outputs['monthly-sc-10'],/NT\$/);await r.subscribe('meta',meta(s,V));assert.equal(r.view().session.liveId,V);assert.equal(r.view().settings.channelLock.bindings[V].source,'onecomme-channel-url');assert.match(r.snapshot().outputs['current-sc-10'],/NT\$30/);await r.subscribe('meta',meta(s,W));assert.equal(r.view().session.liveId,W);assert.doesNotMatch(r.snapshot().outputs['current-sc-10'],/NT\$/);assert.match(r.snapshot().outputs['current-sc-10'],/本場 SC/);await r.subscribe('comments',[comment(W,'two')]);await r.close();const restored=await createRuntime({dir}, {services:[{...s,meta:meta(s,W).data}]});try{assert.equal(restored.view().session.liveId,W);assert.match(restored.snapshot().outputs['current-sc-10'],/NT\$30/);}finally{await restored.close();}}finally{await r.close();await fs.rm(dir,{recursive:true,force:true,maxRetries:5});}});
test('其他頻道、影片網址、偽裝 service、衝突 metadata 不會自動加入',async()=>{const own=service('one',A),other=service('other',B),video={id:'video',url:'https://youtube.com/watch?v='+W,enabled:true},{r,dir}=await setup({services:[own,other,video]});try{for(const m of [meta(other,V),meta(video,W,{channelId:A}),meta({...own,url:other.url},V),meta(own,V,{channelId:B}),meta(own,V,{liveId:W}),{...meta(own,V),type:'twitch'}])await r.subscribe('meta',m);assert.deepEqual(r.view().settings.channelLock.bindings,{});await r.subscribe('comments',[{...comment(V,'fake'),data:{...comment(V,'fake').data,isOwner:true,userId:A}}]);assert.deepEqual(r.view().settings.channelLock.bindings,{});await r.subscribe('meta',meta(own,V));assert.ok(Lock.allows(r.view().settings.channelLock,V));await r.subscribe('services',[{...own,enabled:false},other]);await r.subscribe('meta',meta(own,W));assert.equal(r.view().settings.channelLock.bindings[W],undefined);assert.equal(r.view().session.liveId,undefined);}finally{await r.close();await fs.rm(dir,{recursive:true,force:true,maxRetries:5});}});
test('已綁另一頻道不能被自動覆蓋；更換 service 網址清除舊解析',async()=>{const s=service('one',A),{r,dir}=await setup({services:[s]});try{await r.request({method:'PUT',body:{channelLock:{channelId:A,bindings:{[V]:{channelId:B,source:'manual-confirmation'}}}}});await r.subscribe('meta',meta(s,V));assert.equal(r.view().settings.channelLock.bindings[V].channelId,B);assert.equal(r.view().session.liveId,undefined);await r.subscribe('meta',meta(s,W));await r.subscribe('services',[service('one',B)]);await r.subscribe('meta',meta(s,'live0000003'));assert.equal(r.view().session.liveId,undefined);assert.equal(r.view().settings.channelLock.bindings.live0000003,undefined);}finally{await r.close();await fs.rm(dir,{recursive:true,force:true,maxRetries:5});}});
test('先接頻道後設定鎖定仍可入榜；meta.clear 不刪紀錄',async()=>{const s=service('one',B),{r,dir}=await setup({services:[{...s,meta:meta(s,V).data}]});try{assert.equal(r.view().session.liveId,undefined);await r.request({method:'PUT',body:{channelLock:{channelId:B}}});assert.equal(r.view().session.liveId,V);await r.subscribe('comments',[comment(V,'saved')]);await r.subscribe('meta.clear','one');assert.equal(r.view().session.liveId,undefined);assert.equal(r.events.length,1);assert.match(r.snapshot().outputs['current-sc-10'],/本場 SC/);assert.doesNotMatch(r.snapshot().outputs['current-sc-10'],/saved/);}finally{await r.close();await fs.rm(dir,{recursive:true,force:true,maxRetries:5});}});
test('本機字型資源只保留所選字型；拒絕外部資源與超額',()=>{const data='data:font/ttf;base64,AAEAAA==',s=Theme.normalize({enabled:true,font:'Example',parts:{name:{font:'Other'}},fontAssets:{Example:data,Other:data,Unused:data}});assert.deepEqual(Object.keys(s.fontAssets),['Example','Other']);assert.match(Theme.css(s),/src:url\("data:font/);assert.throws(()=>Theme.normalize({font:'Example',fontAssets:{Example:'https://evil.example/font.ttf'}}));assert.throws(()=>Theme.normalize({font:'Example',fontAssets:{Example:'data:font/ttf;base64,'+'A'.repeat(45000001)}}));});
test('字型讀取 API 要求本機 origin 與憑證，不接受任意路徑',async()=>{let reads=0;const server=createResolverServer({fontData:async id=>{reads++;return {data:'data:font/ttf;base64,AAEAAA=='};}});await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port,origin={Origin:'http://127.0.0.1:11180'},route='/fonts/'+'a'.repeat(64);try{assert.equal((await fetch(base+route,{headers:origin})).status,403);assert.equal((await fetch(base+route,{headers:{Origin:'https://evil.example'}})).status,403);const {credential}=await(await fetch(base+'/session',{headers:origin})).json(),headers={...origin,'X-YT-Session':credential};assert.equal((await fetch(base+route,{headers})).status,200);assert.notEqual((await fetch(base+'/fonts/C:/secret.txt',{headers})).status,200);assert.equal(reads,1);}finally{server.closeAllConnections();await new Promise(r=>server.close(r));}});
