'use strict';const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),os=require('node:os'),path=require('node:path');const c=require('../src/core'),{createRuntime}=require('../src/runtime');
const s={...c.DEFAULT_SETTINGS,rates:{...c.DEFAULT_SETTINGS.rates}};
test('幣別解析',()=>{for(const [text,cur,amt] of [['NT$70','TWD',70],['NT $70','TWD',70],['$70','TWD',70],['¥1,000','JPY',1000]]){const r=c.parsePaidText(text,'TWD');assert.equal(r.currency,cur);assert.equal(r.amount,amt)}assert.equal(c.parsePaidText('$70','USD').currency,'USD')});
test('未知幣別不換算',()=>assert.equal(c.currencyDetails({price:3,unit:'XYZ'},s).amountTwd,null));
test('身份、場次、月榜與排行筆數',()=>{const a=c.normalizeEvent({service:'youtube',data:{timestamp:'2026-09-09T00:00:00Z',id:'1',type:'superchat',userId:'u',displayName:'舊名',liveId:'a',paidText:'NT$70'}},{},s),b=c.normalizeEvent({service:'youtube',data:{timestamp:'2026-09-09T00:00:00Z',id:'2',type:'superchat',userId:'u',displayName:'新名',liveId:'b',paidText:'NT$30'}},{},s),d=c.normalizeEvent({service:'youtube',data:{timestamp:'2026-09-09T00:00:00Z',id:'3',type:'superchat',userId:'v',displayName:'新名',liveId:'b',paidText:'NT$20'}},{},s);const r=c.rank([a,b,d],{kind:'sc',period:'all_time',limit:10});assert.equal(r.length,2);assert.equal(r[0].value,100);assert.equal(c.rank([a,b],{kind:'sc',period:'current',service:'youtube',liveId:'b'}).length,1);assert.equal(c.rank(Array.from({length:12},(_,i)=>({...a,eventId:String(i),userId:String(i),amountTwd:i+1})),{limit:3}).length,3)});
test('贈送與 giftreceived',()=>{const g=c.normalizeEvent({service:'youtube',data:{timestamp:'2026-09-09T00:00:00Z',id:'g',liveId:'gift-live',type:'sponsorgift',userId:'u',giftCount:10}},{},s),r=c.normalizeEvent({service:'youtube',data:{timestamp:'2026-09-09T00:00:00Z',id:'r',liveId:'gift-live',type:'giftreceived',userId:'v',giftCount:1}},{},s);assert.equal(c.rank([g,r],{kind:'gift'})[0].value,10)});
test('OneComme giftType 與留言內贈送數量',()=>{const g=c.normalizeEvent({service:'youtube',data:{timestamp:'2026-09-09T00:00:00Z',id:'g2',giftType:'sponsorgift',userId:'u',name:'贈送者',comment:'贈送了 10 個會員',liveId:'live'}},{},s);assert.equal(g.eventType,'sponsorgift');assert.equal(g.giftCount,10);assert.equal(g.displayName,'贈送者')});
test('格式空格與空白行',()=>assert.equal(c.formatRanking([{displayName:'甲',value:70}],{title:'測試',rankNameSpaces:2,nameValueSpaces:3,blankLines:1}),'【測試】\n\n1.  甲   NT$70\n'));
test('去重與重啟恢復',async()=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),'yt-rank-'));const r=await createRuntime({dir,store:{store:{}}});const x={data:{timestamp:'2026-09-09T00:00:00Z',id:'same',type:'superchat',userId:'u',liveId:'l',paidText:'NT$70'}};await r.subscribe('comments',[x,x]);assert.equal(r.events.length,1);await r.close();const r2=await createRuntime({dir,store:{store:{}}});assert.equal(r2.events.length,1)});
