'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),os=require('node:os');
const H=require('../src/history-import'),{createRuntime}=require('../src/runtime'),Core=require('../src/core'),Lock=require('../channel-lock'),Policy=require('../record-policy');
const A='UC'+'a'.repeat(22),B='UC'+'b'.repeat(22),V='live0000001',W='live0000002',at='2026-09-09T13:00:00.000Z';
const item=(type,id,live=V,extra={})=>({service:'youtube',url:'https://youtube.com/watch?v='+live,data:{id,userId:id,name:'Synthetic',liveId:live,timestamp:at,giftType:type,price:30,unit:'TWD',giftCount:3,...extra},meta:{title:'Synthetic stream',startedAt:'2026-09-09T12:00:00.000Z'}});
const saved=()=>({events:[],settings:{...Core.DEFAULT_SETTINGS,channelLock:Lock.normalize({channelId:A,channelName:'Synthetic channel'})},reset:{at:0,ids:[]}});
const preview={source:'database',from:'2026-09-01',to:'2026-09-30'};
const videoResult=(url,owner=A)=>({source:'youtube-public-metadata',requestUrl:url,liveId:Lock.parseLive(url),channelId:owner,channelName:owner===A?'Own channel':'Other channel',videoTitle:'Public video title',resolvedAt:at});
test('影片資訊相符可匯入，不符後端拒絕，未知必須逐場人工確認',async()=>{
 let clock=0,calls=0;const h=H.createHistoryImport({now:()=>clock,readDatabase:async()=>[item('superchat','one'),item('superchat','two',W),item('superchat','three','live0000003')],resolveVideo:async url=>{calls++;if(url.endsWith('3'))throw Error('Video unavailable');return videoResult(url,url.endsWith('2')?B:A);}}),s=saved(),original=JSON.stringify(s),p=await h.preview(preview,s);
 const query=id=>({token:p.token,channelId:A,liveId:id,consent:true});
 await assert.rejects(h.lookup({...query(V),consent:false},()=>s),/同意/);assert.equal(calls,0);
 let result=await h.lookup(query(V),()=>s);assert.equal(result.sessions[0].verification.status,'match');assert.equal(result.sessions[0].verification.videoTitle,'Public video title');assert.equal(JSON.stringify(s),original);
 clock+=1100;result=await h.lookup(query(W),()=>s);assert.equal(result.sessions[1].verification.status,'mismatch');assert.ok(result.sessions[1].blocked);
 const body={token:p.token,channelId:A,liveIds:[W],manualLiveIds:[W],confirmed:true};assert.throws(()=>h.prepare(body,s),/其他頻道/);
 clock+=1100;result=await h.lookup(query('live0000003'),()=>s);assert.equal(result.sessions[2].verification.status,'unknown');
 assert.throws(()=>h.prepare({...body,liveIds:['live0000003'],manualLiveIds:[]},s),/逐場/);
 assert.equal(h.prepare({...body,liveIds:['live0000003'],manualLiveIds:['live0000003']},s).stats.added,1);
 assert.equal(h.prepare({...body,liveIds:[V],manualLiveIds:[]},s).stats.added,1);
 const next=await h.preview(preview,s);assert.equal(next.sessions[0].verification.status,'unchecked');assert.equal(JSON.stringify(s),original);
});
test('查詢期間不能匯入；頻道變更或重新預覽會丟棄舊查詢',async()=>{
 let done;const h=H.createHistoryImport({readDatabase:async()=>[item('superchat','one')],resolveVideo:url=>new Promise(r=>done=()=>r(videoResult(url)))}),s=saved(),p=await h.preview(preview,s),body={token:p.token,channelId:A,liveId:V,consent:true};
 const pending=h.lookup(body,()=>s);assert.throws(()=>h.prepare({...body,liveIds:[V],manualLiveIds:[V],confirmed:true},s),/查詢中/);
 s.settings.channelLock.channelId=B;done();await assert.rejects(pending,/變動/);
});
test('runtime 查詢不阻塞即時收錄，並忽略客戶端偽造相符結果',async t=>{
 let done;const dir=await fs.mkdtemp(path.join(os.tmpdir(),'rank-history-lookup-')),r=await createRuntime({dir,historyReader:async()=>[item('superchat','archived')],historyVideoResolver:url=>new Promise(resolve=>done=()=>resolve(videoResult(url,B)))});
 t.after(async()=>{await r.close();await fs.rm(dir,{recursive:true,force:true,maxRetries:5,retryDelay:100});});
 await r.request({method:'PUT',body:{channelLock:Lock.bind({channelId:A},V)}});const p=(await r.request({method:'POST',body:{action:'historyPreview',...preview}})).response.history;
 const pending=r.request({method:'POST',body:{action:'historyLookup',token:p.token,channelId:A,liveId:V,consent:true}});
 await r.subscribe('comments',[item('superchat','live-event')]);assert.equal(r.events.length,1);done();const reply=await pending;assert.equal(reply.response.history.sessions[0].verification.status,'mismatch');
 const rejected=await r.request({method:'POST',body:{action:'historyImport',token:p.token,channelId:A,liveIds:[V],manualLiveIds:[V],confirmed:true,verification:{status:'match'}}});assert.equal(rejected.code,400);assert.equal(r.events.length,1);
});
test('SQLite 日期讀取僅讀原檔；Windows 相容讀取器結果一致',async t=>{let DatabaseSync;try{({DatabaseSync}=require('node:sqlite'));}catch{t.skip('fixture creation requires node:sqlite');return;}const dir=await fs.mkdtemp(path.join(os.tmpdir(),'rank-sqlite-history-'));t.after(()=>fs.rm(dir,{recursive:true,force:true,maxRetries:5,retryDelay:100}));const file=path.join(dir,'comments.db'),db=new DatabaseSync(file);db.exec('CREATE TABLE comments (id TEXT, comment JSON, created_at TIMESTAMP)');const inside=item('superchat','inside'),outside=item('superchat','outside',V,{timestamp:'2026-08-01T00:00:00.000Z'});for(const value of [inside,outside])db.prepare('INSERT INTO comments VALUES (?, ?, ?)').run(value.data.id,JSON.stringify(value),value.data.timestamp);db.close();const before=await fs.readFile(file),{readCommentDatabase}=require('../src/history-sqlite'),range=H.dateRange('2026-09-01','2026-09-30');assert.deepEqual(await readCommentDatabase(range,file),[inside]);if(process.platform==='win32')assert.deepEqual(await readCommentDatabase(range,file,true),[inside]);assert.deepEqual(await fs.readFile(file),before);});
test('來源直播 ID 與網址衝突不匯入；已知測試場次不因網址補值而轉正式',()=>{const conflict=item('superchat','wrong');conflict.url='https://youtube.com/watch?v='+W;const tested=item('superchat','known-test');tested.data.liveId='youtube-test';const result=H.collect([conflict,tested],saved().settings,H.dateRange('2026-09-01','2026-09-30'));assert.equal(result.invalid,1);assert.equal(result.sessions[0].events.length,1);assert.equal(result.sessions[0].events[0].explicitTest,true);});
test('歷史預覽只讀取、保留來源標題與時間，數字時間戳依原值轉換',async()=>{const raw=[item('superchat','sc'),item('sponsorgift','gift'),item('giftreceived','recipient'),item('jewel','gem',V,{jewels:5,giftCount:2}),item('normal','normal')],s=saved(),before=JSON.stringify(s);raw[0].data.timestamp=Date.parse(at);const h=H.createHistoryImport({readDatabase:async()=>raw});const p=await h.preview(preview,s);assert.equal(JSON.stringify(s),before);assert.equal(p.sessions.length,1);assert.equal(p.sessions[0].sc,1);assert.equal(p.sessions[0].gift,1);assert.equal(p.sessions[0].received,1);assert.equal(p.sessions[0].firstRecorded,at);assert.equal(p.sessions[0].startedAt,'2026-09-09T12:00:00.000Z');assert.equal(p.sessions[0].title,'Synthetic stream');assert.equal(raw[0].data.timestamp,Date.parse(at));});
test('指定場次、確認與頻道限制；重复匯入不重複加總',async()=>{const h=H.createHistoryImport({readDatabase:async()=>[item('superchat','sc'),item('sponsorgift','gift',W)]}),s=saved(),p=await h.preview(preview,s);const body={token:p.token,channelId:A,liveIds:[V],manualLiveIds:[V],confirmed:true};assert.throws(()=>h.prepare({...body,confirmed:false},s));assert.throws(()=>h.prepare({...body,token:'forged'},s));const result=h.prepare(body,s);assert.equal(result.next.events.length,1);assert.equal(result.stats.added,1);assert.equal(Lock.allows(result.next.settings.channelLock,W),false);const p2=await h.preview(preview,result.next),again=h.prepare({...body,token:p2.token},result.next);assert.equal(again.stats.duplicates,1);assert.equal(again.next.events.length,1);});
test('已綁其他頻道、設定變動、過期預覽都不能直接匯入',async()=>{let clock=0;const h=H.createHistoryImport({readDatabase:async()=>[item('superchat','sc')],now:()=>clock}),s=saved();s.settings.channelLock.bindings[V]={channelId:B,source:'manual-confirmation'};const p=await h.preview(preview,s),body={token:p.token,channelId:A,liveIds:[V],manualLiveIds:[V],confirmed:true};assert.ok(p.sessions[0].blocked);assert.throws(()=>h.prepare(body,s),/另一頻道/);delete s.settings.channelLock.bindings[V];assert.throws(()=>h.prepare(body,s),/變動/);const p2=await h.preview(preview,s);clock=600001;assert.throws(()=>h.prepare({...body,token:p2.token},s),/過期/);});
test('日誌檔支援 JSON array 和 JSONL；拒絕無效格式、日期及超額檔案',()=>{const one=item('superchat','sc');assert.equal(H.parseLogFiles([{text:JSON.stringify([one])},{text:JSON.stringify(one)+'\n'}]).length,2);assert.throws(()=>H.parseLogFiles([{name:'bad.log',text:'invalid'}]),/bad.log/);assert.throws(()=>H.parseLogFiles(Array.from({length:31},()=>({text:''}))));assert.throws(()=>H.dateRange('2026-02-30','2026-03-01'));assert.throws(()=>H.dateRange('2026-09-10','2026-09-01'));assert.throws(()=>H.dateRange('2024-01-01','2026-01-01'));assert.equal(H.dateRange('2026-09-01','2026-09-01').from,'2026-08-31T16:00:00.000Z');});
test('沒有標題／開台時間不虛構；URL 可補直播 ID，日期外事件不匯入',()=>{const one=item('superchat','sc');delete one.meta;delete one.data.liveId;one.name='Connection label is not a stream title';const other=item('superchat','old',V,{timestamp:'2026-08-01T00:00:00.000Z'});const result=H.collect([one,other],saved().settings,H.dateRange('2026-09-01','2026-09-30'));assert.equal(result.sessions[0].events.length,1);assert.equal(result.sessions[0].title,'');assert.equal(result.sessions[0].startedAt,'');assert.equal(result.sessions[0].liveId,V);});
test('同 ID 衝突隔離、清空與測試仍有效，寶石連送更新不新增副本',()=>{const s=saved();s.settings.channelLock=Lock.bind(s.settings.channelLock,V);const old=Core.normalizeEvent(item('superchat','same'),{},s.settings),incoming=Core.normalizeEvent(item('superchat','same',V,{price:99}),{},s.settings),events=[old];H.merge(events,[incoming]);assert.equal(events.length,2);assert.equal(Policy.rank(events.filter(e=>Policy.eligible(e,undefined,s.settings.channelLock)),'sc').length,0);const gem=Core.normalizeEvent(item('jewel','gem',V,{jewels:10,giftCount:1}),{},s.settings),growing=Core.normalizeEvent(item('jewel','gem',V,{jewels:10,giftCount:3}),{},s.settings);const result=H.merge([gem],[growing]);assert.equal(result.updated,1);assert.equal(gem.jewelTotal,30);const tested=Core.normalizeEvent(item('superchat','test'),{},{...s.settings,recordMode:'test'});assert.equal(Policy.eligible(tested,undefined,s.settings.channelLock),false);assert.equal(Policy.eligible(old,()=>true,s.settings.channelLock),false);});
async function runtime(t){const dir=await fs.mkdtemp(path.join(os.tmpdir(),'rank-history-test-'));const r=await createRuntime({dir,historyReader:async()=>[item('superchat','sc'),item('sponsorgift','gift',W)]});t.after(async()=>{await r.close();await fs.rm(dir,{recursive:true,force:true,maxRetries:5,retryDelay:100});});await r.request({method:'PUT',body:{channelLock:{channelId:A}}});return {r,dir};}
test('runtime 匯入前備份，重啟後仍有紀錄與場次設定',async t=>{const {r,dir}=await runtime(t);const p=await r.request({method:'POST',body:{action:'historyPreview',...preview}});assert.equal(r.events.length,0);const result=await r.request({method:'POST',body:{action:'historyImport',token:p.response.history.token,channelId:A,liveIds:[V],manualLiveIds:[V],confirmed:true}});assert.equal(result.code,200);assert.equal(result.response.historyResult.added,1);assert.equal((await fs.readdir(path.join(dir,'data','backups'))).length,1);await r.close();const restored=await createRuntime({dir});try{assert.equal(restored.events.length,1);assert.equal(Lock.allows(restored.view().settings.channelLock,V),true);}finally{await restored.close();}});
test('匯入前備份失敗不更動事件與綁定',async t=>{const {r,dir}=await runtime(t),p=await r.request({method:'POST',body:{action:'historyPreview',...preview}}),rename=fs.rename;fs.rename=async(a,b)=>{if(b.startsWith(path.join(dir,'data','backups')+path.sep))throw Error('SYNTHETIC_BACKUP_FAILURE');return rename(a,b);};try{const result=await r.request({method:'POST',body:{action:'historyImport',token:p.response.history.token,channelId:A,liveIds:[V],manualLiveIds:[V],confirmed:true}});assert.equal(result.code,400);assert.equal(r.events.length,0);assert.equal(Lock.allows(r.view().settings.channelLock,V),false);}finally{fs.rename=rename;}});
