'use strict';
require('node:test')('value position defaults preserve full-width boards and clamp input',()=>{const T=require('../style-theme'),a=require('node:assert/strict');a.equal(T.normalize({}).valuePosition,100);a.equal(T.normalize({valuePosition:1}).valuePosition,40);a.equal(T.normalize({valuePosition:999}).valuePosition,100);a.match(T.css({enabled:true,layout:'aligned',valuePosition:65}),/rank-row\{width:65%/);a.match(T.css({enabled:true,layout:'compact',valuePosition:65}),/rank-row\{width:100%/);});
const nodeTest=require('node:test');
nodeTest('icon mode centers natural-width markers within shared rank column',()=>{const css=require('../style-theme').css({enabled:true,rankMode:'icon'});require('node:assert/strict').match(css,/\.rank-number\{justify-self:center;\}/);});
// Missing emojis retain a slot only in combined mode; icon-only fallback stays compact.
const test=require('node:test'),assert=require('node:assert/strict'),Theme=require('../style-theme'),Output=require('../rank-output');
test('hide leading @ defaults on for old themes and preserves explicit opt-out',()=>{assert.equal(Theme.normalize({}).hideAtPrefix,true);assert.equal(Theme.normalize({hideAtPrefix:false}).hideAtPrefix,false);});
test('display removes only leading @ before truncation, raw identity untouched',()=>{const rows=[{displayName:'@主播@台',userId:'UC-identity',value:10},{displayName:'普通名稱',value:1}];const raw=JSON.stringify(rows);assert.equal(Output.presentation(rows,'sc','monthly',{hideAtPrefix:true,maxNameLength:3}).rows[0].name,'主播@…');assert.equal(Output.presentation(rows,'sc','monthly',{hideAtPrefix:false}).rows[0].name,'@主播@台');assert.equal(JSON.stringify(rows),raw);});
test('all rank modes consume measured shared width without changing compact value layout',()=>{for(const rankMode of ['number','icon','both']){const css=Theme.css({enabled:true,rankMode});assert.match(css,/var\(--rank-column-width,max-content\) minmax\(0,max-content\) max-content/);assert.match(css,/width:max-content;justify-self:start/);}});
test('combined mode reserves emoji column for every rank, other modes do not',()=>{const input={enabled:true,icons:{1:{emoji:'🥇'}}};assert.match(Theme.css({...input,rankMode:'both'}),/grid-template-columns:var\(--rank-icon-column-width,max-content\) max-content/);for(const rankMode of ['icon','number'])assert.doesNotMatch(Theme.css({...input,rankMode}),/grid-template-columns:var\(--rank-icon-column-width/);});
