'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),os=require('node:os'),path=require('node:path');
const {createRuntime}=require('../src/runtime'),{createConfirmationController}=require('../src/native-confirmation');
const A='UC'+'a'.repeat(22),B='UC'+'b'.repeat(22),V='live0000001',W='live0000002',source=(live=V)=>({id:live,url:'https://www.youtube.com/watch?v='+live,enabled:true});
const event=live=>({service:'youtube',data:{type:'superchat',id:'sc-'+live,userId:'viewer',name:'Viewer',liveId:live,price:30,unit:'TWD',timestamp:new Date().toISOString()}});
async function setup(){const dir=await fs.mkdtemp(path.join(os.tmpdir(),'yt-prompt-')),r=await createRuntime({dir,store:{store:{channelLock:{channelId:A}}}},{services:[source()]});return {dir,r,async close(){await r.close();await fs.rm(dir,{recursive:true,force:true,maxRetries:5});}};}
test('新直播彈窗確認加入；支持收錄不等待回答；重啟不重複詢問',async()=>{const t=await setup();try{const [candidate]=t.r.pendingConfirmations();assert.equal(candidate.liveId,V);await t.r.subscribe('comments',[event(V)]);assert.equal(t.r.events.length,1);assert.doesNotMatch(t.r.snapshot().outputs['current-sc-10'],/NT\$/);assert.equal(await t.r.confirmCandidate(candidate,'accept'),true);assert.match(t.r.snapshot().outputs['current-sc-10'],/NT\$30/);assert.equal(t.r.pendingConfirmations().length,0);assert.equal(await t.r.confirmCandidate(candidate,'accept'),false);await t.r.close();const restored=await createRuntime({dir:t.dir},{services:[source()]});try{assert.equal(restored.pendingConfirmations().length,0);}finally{await restored.close();}}finally{await t.close();}});
test('不是此頻道保留事件與略過記憶；手動確認可更正',async()=>{const t=await setup();try{await t.r.subscribe('comments',[event(V)]);await t.r.confirmCandidate(t.r.pendingConfirmations()[0],'reject');assert.equal(t.r.events.length,1);assert.equal(t.r.pendingConfirmations().length,0);await t.r.close();const r=await createRuntime({dir:t.dir},{services:[source()]});try{assert.equal(r.pendingConfirmations().length,0);const lock=require('../channel-lock').bind(r.view().settings.channelLock,V);assert.equal(lock.dismissedLives[V],undefined);await r.request({method:'PUT',body:{channelLock:lock}});assert.match(r.snapshot().outputs['current-sc-10'],/NT\$30/);}finally{await r.close();}}finally{await t.close();}});
test('頻道切換來回、停用、移除重接與偽造 token 的舊回覆無效',async()=>{const t=await setup();try{let p=t.r.pendingConfirmations()[0];assert.equal(await t.r.confirmCandidate({...p,token:'wrong'},'accept'),false);await t.r.request({method:'PUT',body:{channelLock:{channelId:B}}});await t.r.request({method:'PUT',body:{channelLock:{channelId:A}}});assert.equal(await t.r.confirmCandidate(p,'accept'),false);p=t.r.pendingConfirmations()[0];await t.r.subscribe('services',[]);await t.r.subscribe('services',[source()]);assert.equal(await t.r.confirmCandidate(p,'accept'),false);p=t.r.pendingConfirmations()[0];await t.r.request({method:'PUT',body:{channelLock:{channelId:A,popupEnabled:false}}});assert.equal(await t.r.confirmCandidate(p,'accept'),false);assert.equal(t.r.pendingConfirmations().length,0);}finally{await t.close();}});
test('其他頻道固定連線、已綁歸屬、相同場次不產生額外確認',async()=>{const t=await setup();try{await t.r.subscribe('services',[source(),{...source(),id:'duplicate'},{id:'other',url:'https://www.youtube.com/channel/'+B,enabled:true,meta:{url:source(W).url}}]);assert.equal(t.r.pendingConfirmations().length,1);const lock=require('../channel-lock').bind({channelId:B},V);await t.r.request({method:'PUT',body:{channelLock:{...lock,channelId:A}}});assert.equal(t.r.pendingConfirmations().length,0);}finally{await t.close();}});
test('一次一窗、稍後不重複；失效視窗取消，不採用回覆',async()=>{let list=[{key:'a',token:'1'},{key:'b',token:'2'}],time=0,applied=[],warnings=[],dialogs=[];const runtime={pendingConfirmations:()=>list,confirmCandidate:async(c,r)=>{applied.push([c.key,r]);list=list.filter(v=>v.key!==c.key);return true;},setPromptWarning:m=>warnings.push(m)};const c=createConfirmationController(runtime,{autoStart:false,settleMs:10,now:()=>time,show:candidate=>{let resolve;const d={candidate,canceled:false,result:new Promise(r=>resolve=r),resolve:v=>resolve(v),cancel(){this.canceled=true;}};dialogs.push(d);return d;}});try{c.tick();time=11;c.tick();assert.equal(dialogs.length,1);c.tick();assert.equal(dialogs.length,1);dialogs[0].resolve('later');await new Promise(setImmediate);c.tick();time=22;c.tick();assert.equal(dialogs.length,2);assert.equal(dialogs[1].candidate.key,'b');list=[];c.tick();assert.equal(dialogs[1].canceled,true);dialogs[1].resolve('accept');await new Promise(setImmediate);assert.deepEqual(applied,[]);list=[{key:'a',token:'3'}];time=100;c.tick();assert.equal(dialogs.length,2);assert.deepEqual(warnings,[]);}finally{c.close();}});
test('視窗啟動或儲存失敗不反覆彈窗、不自動放行',async()=>{let shows=0,warnings=[];const r={pendingConfirmations:()=>[{key:'a',token:'1'}],setPromptWarning:m=>warnings.push(m),confirmCandidate:async()=>{throw Error('disk failure');}};const c=createConfirmationController(r,{autoStart:false,settleMs:0,show:()=>{shows++;return {result:Promise.resolve('accept'),cancel(){}};}});try{c.tick();c.tick();await new Promise(setImmediate);c.tick();assert.equal(shows,1);assert.equal(warnings.length,1);}finally{c.close();}});
