'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),os=require('node:os'),path=require('node:path'),crypto=require('node:crypto');
const {createStateStore,month}=require('../src/state-store'),{createRuntime}=require('../src/runtime'),Output=require('../rank-output'),Policy=require('../record-policy'),Lock=require('../channel-lock');
const lock=Lock.bind({channelId:'UC'+'a'.repeat(22)},'live0000001');
test('initial cached comments remain retryable when their first commit fails',async t=>{const dataDir=await temp(t),rename=fs.rename;let fail=true,writes=0,r;fs.rename=async(a,b)=>{if(b===path.join(dataDir,'state.json')&&++writes>1&&fail)throw Error('INITIAL_WRITE_FAILED');return rename(a,b);};try{r=await createRuntime({dataDir,retryIntervalMs:25},{comments:[event()]});assert.match(r.view().lastError,/INITIAL_WRITE_FAILED/);assert.equal(r.view().storageHealth.pendingEvents,1);fail=false;for(let i=0;i<100&&r.view().storageHealth.pendingEvents;i++)await new Promise(resolve=>setTimeout(resolve,25));assert.equal(r.events.length,1);assert.equal(r.view().lastError,'');}finally{fail=false;fs.rename=rename;await r?.close();}});
test('failed-write queue caps event count and keeps overflow warning after recovery',async t=>{const {r,dataDir}=await runtime(t,{retryIntervalMs:60000}),rename=fs.rename;let fail=true;fs.rename=async(a,b)=>{if(fail&&b===path.join(dataDir,'state.json'))throw Error('QUEUE_TEST_DISK_FULL');return rename(a,b);};try{const e=event();await assert.rejects(()=>r.subscribe('comments',Array.from({length:10002},()=>e)));assert.equal(r.view().storageHealth.pendingEvents,10000);assert.equal(r.view().storageHealth.droppedEvents,2);assert.ok(r.view().storageHealth.pendingBytes<=16*1024*1024);fail=false;await r.close();assert.equal(r.events.length,1);assert.match(r.view().lastError,/未能保留/);}finally{fail=false;fs.rename=rename;}});
const event=(id='a')=>({service:'youtube',data:{type:'superchat',id,userId:id,liveId:'live0000001',timestamp:new Date().toISOString(),price:30,unit:'TWD'}});
const state=()=>({schemaVersion:3,writeToken:'a'.repeat(64),settings:{channelLock:lock},reset:{},revision:0,themes:{},events:[{eventId:'synthetic',timestamp:'2026-09-01T00:00:00Z'}]});
async function temp(t){const dir=await fs.mkdtemp(path.join(os.tmpdir(),'yt-reliability-'));t.after(()=>fs.rm(dir,{recursive:true,force:true,maxRetries:5,retryDelay:100}));return dir;}
async function runtime(t,extra={}){const dataDir=await temp(t),r=await createRuntime({dataDir,store:{store:{channelLock:lock}},...extra});t.after(()=>r.close());return {r,dataDir};}
test('missing index with existing objects refuses initialization and preserves every recovery file',async t=>{const dir=await temp(t),store=createStateStore(dir);await store.save(state());const previous=await fs.readFile(path.join(dir,'state.previous.json')),objects=await fs.readdir(path.join(dir,'objects'));await fs.unlink(path.join(dir,'state.json'));await assert.rejects(()=>createRuntime({dataDir:dir}),/主索引.*遺失/);assert.deepEqual(await fs.readFile(path.join(dir,'state.previous.json')),previous);assert.deepEqual(await fs.readdir(path.join(dir,'objects')),objects);await assert.rejects(()=>fs.access(path.join(dir,'state.json')));});
test('only backups or previous index also block an unsafe empty initialization',async t=>{for(const name of ['before-migration-test.json','state.previous.json']){const dir=await temp(t);await fs.writeFile(path.join(dir,name),'recovery evidence');await assert.rejects(()=>createRuntime({dataDir:dir}),/主索引/);assert.equal(await fs.readFile(path.join(dir,name),'utf8'),'recovery evidence');}});
test('large valid monthly object loads 200000 events without argument expansion',async t=>{const dir=await temp(t),store=createStateStore(dir);await store.save(state());const disk=JSON.parse(await fs.readFile(path.join(dir,'state.json'))),rows=Array.from({length:200000},(_,index)=>({index,event:{eventId:'e'+index,timestamp:'2026-09-01T00:00:00Z'}})),raw=JSON.stringify(rows),name='events-2026-09-'+crypto.createHash('sha256').update(raw).digest('hex')+'.json';await fs.writeFile(path.join(dir,'objects',name),raw);disk.months=[{month:'2026-09',count:rows.length,file:name}];await fs.writeFile(path.join(dir,'state.json'),JSON.stringify(disk));const loaded=await createStateStore(dir).load();assert.equal(loaded.events.length,200000);assert.equal(loaded.events.at(-1).eventId,'e199999');});
test('short and unsupported years round-trip without poisoning file names',async t=>{assert.equal(month('0001-09-01T00:00:00Z'),'0001-09');for(const v of ['+010000-01-01T00:00:00Z','0000-01-01T00:00:00Z','bad',null,0,''])assert.equal(month(v),'unknown');const dir=await temp(t),store=createStateStore(dir),value=state();value.events=['0001-09-01T00:00:00Z','+010000-01-01T00:00:00Z','bad'].map(timestamp=>({timestamp}));await store.save(value);assert.deepEqual((await createStateStore(dir).load()).events,value.events);});
test('failed event writes reach view and OBS health, retry later persists exactly once',async t=>{const {r,dataDir}=await runtime(t,{retryIntervalMs:25});const rename=fs.rename;let fail=true;fs.rename=async(a,b)=>{if(fail&&b===path.join(dataDir,'state.json'))throw Error('SIMULATED_DISK_FULL');return rename(a,b);};try{const e=event();await assert.rejects(()=>r.subscribe('comments',{comments:[e,e]}));assert.equal(r.events.length,0);assert.match(r.view().lastError,/SIMULATED_DISK_FULL/);assert.equal(r.view().storageHealth.pendingEvents,2);assert.match(r.snapshot().storageHealth.error,/SIMULATED_DISK_FULL/);await r.subscribe('services',[]);assert.match(r.view().lastError,/SIMULATED_DISK_FULL/);const poll=await r.request({method:'POST',body:{action:'poll',dataRevision:r.view().dataRevision}});assert.equal(poll.response.events,undefined);assert.match(poll.response.lastError,/SIMULATED_DISK_FULL/);assert.equal((await r.request({method:'POST',body:{action:'reset'}})).code,400);fail=false;for(let i=0;i<100&&r.view().storageHealth.pendingEvents;i++)await new Promise(resolve=>setTimeout(resolve,25));assert.equal(r.events.length,1);assert.equal(r.view().storageHealth.pendingEvents,0);assert.equal(r.view().lastError,'');await r.close();const restarted=await createRuntime({dataDir});assert.equal(restarted.events.length,1);await restarted.close();}finally{fail=false;fs.rename=rename;}});
test('oversized pending event is rejected with a persistent explicit gap warning',async t=>{const {r}=await runtime(t);const e=event();e.data.comment='x'.repeat(17*1024*1024);await r.subscribe('comments',[e]);assert.equal(r.events.length,0);assert.equal(r.view().storageHealth.pendingBytes,0);assert.equal(r.view().storageHealth.droppedEvents,1);assert.match(r.view().lastError,/未能保留/);await r.subscribe('comments',[event('ok')]);assert.equal(r.events.length,1);assert.match(r.view().lastError,/未能保留/);});
test('poll omits unchanged records but returns updates and refreshes after restart',async t=>{const {r,dataDir}=await runtime(t);const first=(await r.request({method:'POST',body:{action:'poll'}})).response;assert.deepEqual(first.events,[]);assert.equal((await r.request({method:'POST',body:{action:'poll',dataRevision:first.dataRevision}})).response.events,undefined);await r.subscribe('comments',[event()]);assert.equal((await r.request({method:'POST',body:{action:'poll',dataRevision:first.dataRevision}})).response.events.length,1);const revision=r.view().dataRevision;await r.close();const next=await createRuntime({dataDir});assert.equal((await next.request({method:'POST',body:{action:'poll',dataRevision:revision}})).response.events.length,1);await next.close();});
test('one snapshot ranks each period/kind once and runtime cache expires on changes and Taiwan rollover',async t=>{let ranks=0;Output.snapshot({events:[],settings:{timezone:'Asia/Taipei'},session:{service:'youtube',liveId:'live0000001'},channelLock:lock,isReset:()=>false}, {...Policy,rank(...args){ranks++;return Policy.rank(...args);}});assert.equal(ranks,9);let now=Date.parse('2026-09-30T15:59:59Z');const {r}=await runtime(t,{clock:()=>now}),original=Output.snapshot;let builds=0;Output.snapshot=(...args)=>{builds++;return original(...args);};try{assert.equal(r.snapshot().month,'2026-09');r.snapshot();r.view();assert.equal(builds,1);now=Date.parse('2026-09-30T16:00:00Z');assert.equal(r.snapshot().month,'2026-10');assert.equal(builds,2);await r.subscribe('services',[{id:'s',enabled:true,url:'https://youtube.com/watch?v=live0000001'}]);r.snapshot();assert.equal(builds,3);await r.subscribe('comments',[event()]);r.snapshot();assert.equal(builds,4);await r.request({method:'POST',body:{action:'styles',kind:'sc',period:'monthly',expectedRevision:r.snapshot().styleRevision,value:{enabled:true,titles:{monthly:'Synthetic'}}}});r.snapshot();assert.equal(builds,5);await r.request({method:'POST',body:{action:'reset'}});r.snapshot();assert.equal(builds,6);}finally{Output.snapshot=original;}});
