'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),os=require('node:os'),path=require('node:path'),Lock=require('../channel-lock'),{createRuntime}=require('../src/runtime');
const A='UC'+'a'.repeat(22),B='UC'+'b'.repeat(22),V='live0000001',service={id:'one',url:'https://www.youtube.com/channel/'+A,enabled:true},meta={type:'youtube',service,data:{url:'https://www.youtube.com/watch?v='+V,title:'Local stream title'}};
const comment=id=>({service:'youtube',data:{type:'superchat',id,userId:id,name:id,liveId:V,timestamp:new Date().toISOString(),price:30,unit:'TWD'}});
test('事件歸屬判斷不複製標題目錄；無效來源不放行',()=>{const lock=Lock.bind({channelId:A},V);Object.defineProperty(lock,'videoCatalog',{get(){throw Error('Catalog must not be scanned per event');}});assert.equal(Lock.allows(lock,V),true);lock.bindings[V].source='untrusted';assert.equal(Lock.allows(lock,V),false);});
async function setup(t,extra={}){const dir=await fs.mkdtemp(path.join(os.tmpdir(),'rank-membership-')),r=await createRuntime({dir,store:{store:{channelLock:{channelId:A}}},...extra},{services:[service]});t.after(async()=>{await r.close();await fs.rm(dir,{recursive:true,force:true,maxRetries:5,retryDelay:100});});return {r,dir};}
const change=(r,operation,extra={})=>r.request({method:'POST',body:{action:'sessionMembership',liveId:V,channelId:A,operation,confirmed:true,...extra}});
test('查詢中更換頻道時不保存過期結果',async t=>{let done;const {r}=await setup(t,{historyVideoResolver:url=>new Promise(resolve=>done=()=>resolve({source:'youtube-public-metadata',requestUrl:url,liveId:V,channelId:A,channelName:'Own',videoTitle:'Old query',resolvedAt:new Date().toISOString()}))});const pending=r.request({method:'POST',body:{action:'sessionLookup',liveId:V,channelId:A,consent:true}});await r.request({method:'PUT',body:{channelLock:{channelId:B}}});done();assert.equal((await pending).code,400);assert.equal(r.view().settings.channelLock.videoCatalog[V],undefined);});
test('移出與恢復不把測試事件改為正式',async t=>{const {r}=await setup(t,{store:{store:{recordMode:'test',channelLock:{channelId:A}}}});await r.subscribe('meta',meta);await r.subscribe('comments',[comment('test-event')]);await change(r,'remove');await change(r,'join');assert.equal(r.events[0].recordMode,'test');assert.doesNotMatch(r.snapshot().outputs['monthly-sc-10'],/NT\$30/);});
test('反覆移出／重新加入不重複事件；阻止自動加回、重啟保留、更新各期與 TXT',async t=>{const {r,dir}=await setup(t);await r.subscribe('meta',meta);await r.subscribe('comments',[comment('one')]);const original=JSON.stringify(r.events);assert.equal(r.view().settings.channelLock.videoCatalog[V].title,'Local stream title');
 for(let i=0;i<3;i++){assert.equal((await change(r,'remove')).code,200);assert.equal(JSON.stringify(r.events),original);await r.subscribe('meta',meta);await r.request({method:'POST',body:{action:'sync'}});assert.equal(Lock.allows(r.view().settings.channelLock,V),false);assert.equal(r.pendingConfirmations().length,0);for(const period of ['current','monthly','all'])if(r.snapshot().outputs[period+'-sc-10'])assert.doesNotMatch(r.snapshot().outputs[period+'-sc-10'],/NT\$30/);assert.doesNotMatch(await fs.readFile(path.join(dir,'output','monthly_sc_top10.txt'),'utf8'),/NT\$30/);assert.equal((await change(r,'join')).code,200);assert.equal(JSON.stringify(r.events),original);assert.match(r.snapshot().outputs['monthly-sc-10'],/NT\$30/);}
 await change(r,'remove');await r.close();const restored=await createRuntime({dir},{services:[service]});try{await restored.subscribe('meta',meta);assert.equal(Lock.allows(restored.view().settings.channelLock,V),false);assert.equal(restored.events.length,1);assert.equal((await change(restored,'join')).code,200);assert.equal(restored.events.length,1);}finally{await restored.close();}
});
test('加入需確認與相同頻道，拒絕外台；備份失敗不移除',async t=>{const {r}=await setup(t);await r.subscribe('meta',meta);await r.subscribe('comments',[comment('one')]);for(const extra of [{confirmed:false},{channelId:B},{liveId:'invalid'}])assert.equal((await change(r,'remove',extra)).code,400);assert.ok(Lock.allows(r.view().settings.channelLock,V));
 const rename=fs.rename;fs.rename=async(a,b)=>{if(b.includes(path.sep+'backups'+path.sep))throw Error('SYNTHETIC_BACKUP_FAILURE');return rename(a,b);};try{assert.equal((await change(r,'remove')).code,400);assert.ok(Lock.allows(r.view().settings.channelLock,V));assert.equal(r.events.length,1);}finally{fs.rename=rename;}
 const lock=Lock.remember(r.view().settings.channelLock,V,{title:'Other',source:'youtube-public-metadata',channelId:B});assert.throws(()=>Lock.bind(lock,V),/其他頻道/);
});
test('查詢只存本機標題，無同意不查；等待查詢仍可收錄，重啟保留',async t=>{let done,calls=0;const {r,dir}=await setup(t,{historyVideoResolver:url=>{calls++;return new Promise(resolve=>done=()=>resolve({source:'youtube-public-metadata',requestUrl:url,liveId:V,channelId:A,channelName:'Own',videoTitle:'Public title',resolvedAt:new Date().toISOString()}));}});await r.subscribe('comments',[comment('before')]);const body={action:'sessionLookup',liveId:V,channelId:A,consent:true};assert.equal((await r.request({method:'POST',body:{...body,consent:false}})).code,400);assert.equal(calls,0);const pending=r.request({method:'POST',body});await r.subscribe('comments',[comment('during')]);done();assert.equal((await pending).code,200);assert.equal(r.events.length,2);assert.equal(Lock.allows(r.view().settings.channelLock,V),false);await r.close();const restored=await createRuntime({dir});try{assert.equal(restored.view().settings.channelLock.videoCatalog[V].title,'Public title');assert.equal(restored.events.length,2);}finally{await restored.close();}
});
test('移出再加入不放行已清空紀錄；重複移出冪等',async t=>{const {r}=await setup(t);await r.subscribe('meta',meta);await r.subscribe('comments',[comment('one')]);await r.request({method:'POST',body:{action:'reset'}});await change(r,'remove');const rev=r.view().revision;await change(r,'remove');assert.equal(r.view().revision,rev);await change(r,'join');assert.doesNotMatch(r.snapshot().outputs['monthly-sc-10'],/NT\$30/);assert.equal(r.events.length,1);});
