'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),os=require('node:os'),path=require('node:path'),zlib=require('node:zlib');
const {createStateStore,month}=require('../src/state-store');
const fixture=()=>({schemaVersion:3,writeToken:'a'.repeat(64),revision:0,settings:{},reset:{},themes:{sc:{image:'synthetic-image'}},events:[{timestamp:'2026-01-31T16:01:00Z',eventId:'a'},{timestamp:'2026-01-01T00:00:00Z',eventId:'b'},{timestamp:'bad',eventId:'c'}]});
test('暫時鎖住舊物件時有限重試，只整理未被現行或前一版引用的物件',async t=>{const dir=await temp(t),store=createStateStore(dir),value=fixture();await store.save(value);await store.save({...value,events:[...value.events,{timestamp:'2026-02-01T00:00:00Z',eventId:'next'}]});const unlink=fs.unlink;let denied=0;fs.unlink=async file=>{if(file.startsWith(path.join(dir,'objects')+path.sep)&&denied++===0){const error=Error('SYNTHETIC_BUSY');error.code='EBUSY';throw error;}return unlink(file);};try{await store.save({...value,events:[]});assert.ok(denied>=2);assert.equal((await store.usage()).maintenanceWarning,'');assert.deepEqual((await createStateStore(dir).load()).events,[]);}finally{fs.unlink=unlink;}});
test('restoring a v3 full backup also replaces stale previous-manifest references',async t=>{const dir=await temp(t),value=fixture(),store=createStateStore(dir);await store.save(value);await store.save({...value,themes:{new:true}});await fs.writeFile(path.join(dir,'state.json'),JSON.stringify(value));const restored=createStateStore(dir);await restored.load();await restored.save(value);const previous=JSON.parse(await fs.readFile(path.join(dir,'state.previous.json')));for(const ref of [previous.themes,...previous.months.map(x=>x.file)])await fs.access(path.join(dir,'objects',ref));assert.deepEqual(await createStateStore(dir).load(),value);});
async function temp(t){const dir=await fs.mkdtemp(path.join(os.tmpdir(),'yt-store-'));t.after(()=>fs.rm(dir,{recursive:true,force:true,maxRetries:5,retryDelay:100}));return dir;}
test('Taipei month buckets preserve order, invalid dates, settings, themes and token',async t=>{assert.equal(month('2026-01-31T16:01:00Z'),'2026-02');const dir=await temp(t),store=createStateStore(dir),value=fixture();await store.save(value);assert.deepEqual(await createStateStore(dir).load(),value);const disk=JSON.parse(await fs.readFile(path.join(dir,'state.json')));assert.equal(disk.schemaVersion,4);assert.equal(disk.months.length,3);assert.equal(disk.events,undefined);assert.ok(disk.themes.endsWith('.json'));});
test('existing schema 3 is backed up unchanged before conversion; restart preserves all data',async t=>{const dir=await temp(t),value=fixture(),raw=JSON.stringify(value);await fs.writeFile(path.join(dir,'state.json'),raw);const store=createStateStore(dir);assert.deepEqual(await store.load(),value);await store.save(value);const backups=(await fs.readdir(dir)).filter(x=>x.startsWith('before-storage-v4-'));assert.equal(backups.length,1);assert.equal(await fs.readFile(path.join(dir,backups[0]),'utf8'),raw);assert.deepEqual(await createStateStore(dir).load(),value);});
test('new events do not rewrite unchanged months or appearance; objects remain bounded',async t=>{const dir=await temp(t),store=createStateStore(dir),value=fixture();await store.save(value);const first=JSON.parse(await fs.readFile(path.join(dir,'state.json'))),paths=[first.themes,first.months.find(x=>x.month==='2026-01').file];const stats=await Promise.all(paths.map(p=>fs.stat(path.join(dir,'objects',p))));for(let i=0;i<10;i++){value.events.push({timestamp:'2026-02-01T00:00:00Z',eventId:'new'+i});value.revision++;await store.save(value);}for(let i=0;i<paths.length;i++)assert.equal((await fs.stat(path.join(dir,'objects',paths[i]))).mtimeMs,stats[i].mtimeMs);const names=await fs.readdir(path.join(dir,'objects'));assert.ok(names.length<=5,JSON.stringify({names,warning:(await store.usage()).maintenanceWarning,current:JSON.parse(await fs.readFile(path.join(dir,'state.json'))),previous:JSON.parse(await fs.readFile(path.join(dir,'state.previous.json')))}));assert.deepEqual(await createStateStore(dir).load(),value);});
test('corruption fails closed and does not overwrite the manifest',async t=>{const dir=await temp(t),store=createStateStore(dir);await store.save(fixture());const raw=await fs.readFile(path.join(dir,'state.json'),'utf8'),disk=JSON.parse(raw);await fs.writeFile(path.join(dir,'objects',disk.themes),'{}');await assert.rejects(()=>createStateStore(dir).load(),/完整性/);assert.equal(await fs.readFile(path.join(dir,'state.json'),'utf8'),raw);});
test('failed commit leaves previous data readable, retry succeeds',async t=>{const dir=await temp(t),store=createStateStore(dir),value=fixture();await store.save(value);const original=fs.rename;fs.rename=async(a,b)=>{if(b===path.join(dir,'state.json'))throw Error('simulated disk failure');return original(a,b);};try{await assert.rejects(()=>store.save({...value,events:[]}));}finally{fs.rename=original;}assert.deepEqual(await createStateStore(dir).load(),value);await store.save({...value,events:[]});assert.deepEqual((await createStateStore(dir).load()).events,[]);});
test('gzip backup deduplicates; cleanup requires confirmation and preserves data + protected backups',async t=>{const dir=await temp(t),store=createStateStore(dir),value=fixture();await store.save(value);await fs.writeFile(path.join(dir,'before-migration-protected.json'),'protected');const one=await store.backup(value);assert.equal((await store.backup(value)).reused,true);assert.deepEqual(JSON.parse(zlib.gunzipSync(await fs.readFile(path.join(dir,'backups',one.name)))),value);for(let i=0;i<7;i++)await store.backup({...value,revision:i+1});await assert.rejects(()=>store.cleanup(false));const done=await store.cleanup(true);assert.equal(done.removed,3);assert.equal((await store.usage()).backups.length,5);assert.equal(await fs.readFile(path.join(dir,'before-migration-protected.json'),'utf8'),'protected');assert.deepEqual(await createStateStore(dir).load(),value);});
