'use strict';
const fs=require('node:fs'),fsp=require('node:fs/promises'),path=require('node:path'),os=require('node:os'),assert=require('node:assert/strict');
const {chromium}=require(process.env.YT_RANK_PLAYWRIGHT||'playwright'),root=path.resolve(__dirname,'..'),{createRuntime}=require('../src/runtime'),{createResolverServer}=require('./resolver-server'),Lock=require('../channel-lock'),Theme=require('../style-theme');
const updateState={current:'0.9.0',automatic:false,busy:false,phase:'idle',lastChecked:0,available:null,ready:false};let updateChecks=0,updateDownloads=0,updateInstalls=0;const updater={status:()=>updateState,savePrefs:async automatic=>Object.assign(updateState,{automatic}),check:async()=>{updateChecks++;return Object.assign(updateState,{lastChecked:1,available:{version:'0.9.1',notes:'Isolated update fixture'}});},stage:async()=>{updateDownloads++;return Object.assign(updateState,{phase:'ready',ready:true});},install:async()=>{updateInstalls++;return Object.assign(updateState,{phase:'waiting',ready:false});}};
(async()=>{let lookups=0,videoLookups=0;const dir=await fsp.mkdtemp(path.join(os.tmpdir(),'yt-board-ui-')),V='live0000001',runtime=await createRuntime({dataDir:dir,historyReader:async()=>[1,2,3].map(i=>({service:'youtube',data:{type:'superchat',id:'archived-'+i,userId:'archived-'+i,name:'Archived '+i,liveId:'history000'+i,timestamp:new Date().toISOString(),price:50,unit:'TWD'},meta:{title:'Local archived title '+i}})),historyVideoResolver:async url=>{videoLookups++;if(url.endsWith('3'))throw Error('Video unavailable');return {source:'youtube-public-metadata',requestUrl:url,liveId:Lock.parseLive(url),channelId:'UC'+(url.endsWith('2')?'b':'a').repeat(22),channelName:url.endsWith('2')?'Other channel':'Own channel',videoTitle:'Public title '+url.slice(-1),resolvedAt:new Date().toISOString()};},store:{store:{channelLock:Lock.bind({channelId:'UC'+'a'.repeat(22)},V)}}}),server=createResolverServer({runtime,updater,fonts:async()=>[],resolveChannel:async url=>{lookups++;return {source:'youtube-public-metadata',requestUrl:url,channelId:'UC'+'a'.repeat(22),channelName:'隔離查詢頻道',liveId:'',resolvedAt:new Date().toISOString()};}});await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;
try{
await runtime.subscribe('comments',Array.from({length:10},(_,i)=>({service:'youtube',data:{type:'superchat',id:'test-'+i,userId:'test-'+i,name:'@Test '+i,liveId:V,timestamp:new Date().toISOString(),price:10+i,unit:'TWD'}})));
browser=await chromium.launch({headless:true,channel:process.env.YT_RANK_BROWSER||'msedge'});const ctx=await browser.newContext({viewport:{width:1280,height:900}}),errors=[],external=[];
await ctx.route('**/*',async route=>{const req=route.request(),u=new URL(req.url());if(u.origin==='http://127.0.0.1:11181'){const r=await fetch('http://127.0.0.1:'+server.address().port+u.pathname,{method:req.method(),headers:{Origin:'http://127.0.0.1:11180','Content-Type':'application/json','X-YT-Session':req.headers()['x-yt-session']||''},body:['POST','PUT'].includes(req.method())?req.postData():undefined});return route.fulfill({status:r.status,contentType:'application/json',body:await r.text()});}if(u.origin==='http://127.0.0.1:11180'&&u.pathname.startsWith('/test/')){const file=path.resolve(root,u.pathname.slice(6));if(file.startsWith(root+path.sep)&&fs.existsSync(file)&&fs.statSync(file).isFile())return route.fulfill({path:file});}external.push(req.url());return route.abort();});
const page=await ctx.newPage();page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());await page.goto('http://127.0.0.1:11180/test/index.html');await page.locator('#backgroundNotice[data-state=ready]').waitFor();
assert.equal(await page.locator('html').getAttribute('data-ui-theme'),'dark');
await page.locator('#managementTheme').selectOption('light');await page.reload();await page.locator('#backgroundNotice[data-state=ready]').waitFor();assert.equal(await page.locator('html').getAttribute('data-ui-theme'),'light');
await page.locator('#managementTheme').selectOption('system');await page.emulateMedia({colorScheme:'dark'});await page.waitForFunction(()=>document.documentElement.dataset.uiTheme==='dark');await page.emulateMedia({colorScheme:'light'});await page.waitForFunction(()=>document.documentElement.dataset.uiTheme==='light');await page.locator('#managementTheme').selectOption('dark');
for(const tab of ['overview','events','records','exports','ranking','settings','appearance']){await page.locator('[data-tab="'+tab+'"]').click();assert.ok(await page.locator('#'+tab).isVisible());}
await page.locator('[data-tab=appearance]').click();await page.locator('#updateStatus').filter({hasText:'目前 v0.9.0'}).waitFor();assert.equal(updateChecks,0);await page.locator('#updateAutomatic').check();await page.waitForFunction(()=>!document.querySelector('#updateCheck').disabled);assert.equal(updateState.automatic,true);await page.locator('#updateCheck').click();await page.locator('#updateStatus').filter({hasText:'可更新至 v0.9.1'}).waitFor();assert.equal(updateChecks,1);await page.locator('#updateDownload').click();await page.locator('#updateStatus').filter({hasText:'更新包已備妥'}).waitFor();assert.equal(updateDownloads,1);await page.locator('#updateInstall').click();await page.locator('#updateStatus').filter({hasText:'更新視窗已開啟'}).waitFor();assert.equal(updateInstalls,1);await page.screenshot({path:path.join(os.tmpdir(),'yt-v090-update-ui.png')});
assert.equal(lookups,0);await page.locator('[data-tab=records]').click();
assert.equal(await page.locator('#channelRegion,#autoChannelRegion,#nativePromptRegion,#manualLiveSettings,#sessionManager.ui-region').count(),5);
assert.equal(await page.locator('#manualLiveSettings').getAttribute('open'),null);await page.locator('#manualLiveSettings > summary').click();assert.equal(await page.locator('#confirmChannelLive').isVisible(),true);assert.equal(await page.locator('#channelLiveInput').isVisible(),true);await page.locator('#manualLiveSettings > summary').click();
await page.locator('#channelSetup').evaluate(e=>e.open=false);
for(const theme of ['light','dark']){await page.locator('#managementTheme').selectOption(theme);await page.locator('main').evaluate(e=>e.scrollTop=0);await page.screenshot({path:path.join(os.tmpdir(),'yt-v082-sections-'+theme+'.png')});assert.equal(await page.locator('#nativePromptRegion .region-caution').isVisible(),true);assert.equal(await page.locator('#nativePromptRegion .section-help p').isVisible(),false);}
for(const width of [850,375]){await page.setViewportSize({width,height:900});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'section width '+width);}await page.setViewportSize({width:1280,height:900});
await page.locator('[data-tab=ranking]').click();await page.locator('#kind').selectOption('gift');await page.locator('#period').selectOption('monthly');
for(const theme of ['dark','light']){await page.locator('#managementTheme').selectOption(theme);assert.equal(await page.locator('#rankingExplanation').isVisible(),true);assert.equal(await page.locator('#preview').isVisible(),false);const colors=await page.locator('#rankingExplanation').evaluate(e=>[getComputedStyle(e).backgroundColor,getComputedStyle(e).color]);assert.deepEqual(colors,theme==='dark'?['rgb(39, 36, 58)','rgb(230, 222, 250)']:['rgb(243, 240, 255)','rgb(51, 43, 80)']);assert.match(await page.locator('.empty-state-title').innerText(),/尚未保存|目前沒有/);await page.screenshot({path:path.join(os.tmpdir(),'yt-v083-empty-'+theme+'.png')});}
await page.locator('#rankingExplanation summary').click();assert.equal(await page.locator('.empty-state-detail').isVisible(),true);await page.locator('#kind').selectOption('sc');assert.equal(await page.locator('#rankingExplanation').isVisible(),false);assert.equal(await page.locator('#preview').isVisible(),true);await page.locator('#managementTheme').selectOption('dark');await page.locator('[data-tab=records]').click();
if(process.env.YT_LAYOUT_ONLY==='1'){console.log(JSON.stringify({ok:true,checks:['five regions','manual disclosure','safety note visible','details folded','light/dark','narrow','empty ranking contrast and populated transition'],errors}));assert.deepEqual(errors,[]);return;}
if(!await page.locator('#channelIdInput').isVisible())await page.locator('#channelSetup > summary').click();
await page.locator('#channelIdInput').fill('https://www.youtube.com/@%E6%B8%AC%E8%A9%A6');await page.locator('#saveChannelLock').click();await page.locator('#channelSetupNotice').filter({hasText:'需要先查詢'}).waitFor();assert.equal(lookups,0);
await page.locator('#queryChannel').click();await page.locator('#channelSetupNotice').filter({hasText:'先勾選'}).waitFor();assert.equal(lookups,0);
await page.locator('#channelLookupConsent').check();await page.locator('#queryChannel').click();await page.locator('#channelLookupResult').waitFor();assert.equal(lookups,1);
assert.equal(await page.locator('#channelLookupName').innerText(),'隔離查詢頻道');assert.notEqual(runtime.view().settings.channelLock.channelName,'隔離查詢頻道');
await page.locator('#useChannelLookup').click();try{await page.locator('#channelSetupNotice').filter({hasText:'已儲存'}).waitFor({timeout:5000});}catch(e){console.error(JSON.stringify({notice:await page.locator('#channelSetupNotice').textContent(),saved:runtime.view().settings.channelLock.channelName,errors}));throw e;}assert.equal(runtime.view().settings.channelLock.channelName,'隔離查詢頻道');
await page.reload();await page.locator('#backgroundNotice[data-state=ready]').waitFor();await page.locator('[data-tab=records]').click();assert.equal(await page.locator('#channelLookupConsent').isChecked(),false);assert.equal(lookups,1);assert.equal(await page.locator('#channelIdInput').inputValue(),'UC'+'a'.repeat(22));
await page.locator('[data-tab=settings]').click();assert.equal(await page.locator('.board-card').count(),9);assert.equal(await page.locator('#studioScope,#studioPeriod,#studioKind,#obsPeriod').count(),0);
assert.equal(await page.locator('#appearance #txtOnlySettings').count(),0);assert.equal(await page.locator('#settings #txtOnlySettings').count(),1);await page.locator('#txtOnlySettings > summary').click();await page.locator('#txtOnlySettings [name=rankNameSpaces]').fill('7');await page.locator('#saveTxtSettings').click();await page.waitForFunction(()=>document.querySelector('#settingsForm').dataset.dirty!=='true');assert.equal(runtime.view().settings.rankNameSpaces,7);await page.reload();await page.locator('#backgroundNotice[data-state=ready]').waitFor();await page.locator('[data-tab=settings]').click();assert.equal(await page.locator('#txtOnlySettings [name=rankNameSpaces]').inputValue(),'7');assert.equal(await page.locator('[name=rankNameSpaces]').count(),1);
const obs=await ctx.newPage();await obs.goto('http://127.0.0.1:11180/test/obs-live.html#'+new URLSearchParams({sync:runtime.readToken,kind:'sc',period:'monthly',top:'3'}));await obs.waitForFunction(()=>document.querySelectorAll('.rank-row').length===3);
assert.equal(await obs.locator('html').getAttribute('data-ui-theme'),null);
await page.locator('[data-board="sc:monthly"] .board-edit').click();await page.locator('#themeTitle_monthly').fill('Custom SC');await page.locator('#studioTop').selectOption('5');await page.locator('#applyTheme').click();await page.locator('#studioSavedState').filter({hasText:'已儲存'}).waitFor();await obs.waitForFunction(()=>document.querySelectorAll('.rank-row').length===5);assert.match(await obs.locator('.rank-title').innerText(),/Custom SC/);assert.equal(Boolean(Theme.select(runtime.styles,'sc','current').enabled),false);
assert.equal(await page.locator('#themeHideAtPrefix').isChecked(),true);assert.equal((await obs.locator('.rank-name').first().innerText()).startsWith('@'),false);await page.locator('#nameAdvanced > summary').click();await page.locator('#themeHideAtPrefix').uncheck();assert.equal((await page.locator('#studioPreview .rank-name').first().innerText()).startsWith('@'),true);await page.locator('#applyTheme').click();await obs.waitForFunction(()=>document.querySelector('.rank-name').textContent.startsWith('@'));await page.reload();await page.locator('#backgroundNotice[data-state=ready]').waitFor();await page.locator('[data-tab=settings]').click();await page.locator('[data-board="sc:monthly"] .board-edit').click();assert.equal(await page.locator('#themeHideAtPrefix').isChecked(),false);await page.locator('#nameAdvanced > summary').click();await page.locator('#themeHideAtPrefix').check();await page.locator('#applyTheme').click();await obs.waitForFunction(()=>!document.querySelector('.rank-name').textContent.startsWith('@'));assert.equal(runtime.events[0].displayName,'@Test 0');
await page.locator('#copyAppearance').click();await page.locator('#copyTargets input[value="gift:monthly"]').check();await page.locator('#confirmCopyAppearance').click();await page.locator('.board-copy-dialog').waitFor({state:'hidden'});assert.equal(Theme.select(runtime.styles,'gift','monthly').titles.monthly,'');
await page.locator('#editor-tab-text').click();await page.locator('#themeRankIcons > summary').click();assert.equal(await page.locator('#rankIconFile1').count(),0);assert.equal(await page.locator('#themeImageFile').count(),1);
await page.locator('#rankEmoji1').fill('👑');await page.locator('#defaultRankEmoji2').click();await page.locator('#rankEmoji3').fill('👩🏽‍🚀');await page.locator('#themeRankMode').selectOption('icon');
await page.locator('#editor-tab-layout').click();await page.locator('#themeLayout').selectOption('aligned');assert.equal(await page.locator('#themeValueGap').isVisible(),false);assert.equal(await page.locator('#themeValuePosition').isVisible(),true);const originalRight=await page.locator('#studioPreview .rank-value').first().evaluate(e=>e.getBoundingClientRect().right);await page.locator('#themeValuePosition').evaluate(e=>e.value='65');await page.locator('#themeValuePosition').dispatchEvent('input');assert.ok(await page.locator('#studioPreview .rank-value').first().evaluate(e=>e.getBoundingClientRect().right)<originalRight-20);await page.locator('#applyTheme').click();await page.waitForFunction(()=>document.querySelector('#studioSavedState').textContent==='已儲存在本機');await page.reload();await page.locator('#backgroundNotice[data-state=ready]').waitFor();await page.locator('[data-tab=settings]').click();await page.locator('[data-board="sc:monthly"] .board-edit').click();await page.locator('#editor-tab-layout').click();assert.equal(await page.locator('#themeValuePosition').inputValue(),'65');await page.screenshot({path:path.join(os.tmpdir(),'yt-v087-value-position.png')});await page.locator('#themeLayout').selectOption('compact');assert.equal(await page.locator('#themeValueGap').isVisible(),true);assert.equal(await page.locator('#themeValuePosition').isVisible(),false);await page.locator('#editor-tab-text').click();
await page.locator('#themeRankIcons').evaluate(e=>e.open=true);
const aligned=async target=>target.waitForFunction(()=>{const names=[...document.querySelectorAll('#studioPreview .rank-name,#output .rank-name')];if(names.length<4)return false;const left=names.map(n=>n.getBoundingClientRect().left);return Math.max(...left)-Math.min(...left)<1;});
await page.locator('#studioMockTen').check();for(const mode of ['both','icon','number']){await page.locator('#themeRankMode').selectOption(mode);await aligned(page);if(mode==='both')await page.waitForFunction(()=>{const x=[...document.querySelectorAll('#studioPreview .rank-number-text')].map(n=>n.getBoundingClientRect().left);return Math.max(...x)-Math.min(...x)<1;});assert.equal(await page.locator('#studioPreview .rank-row').count(),10);}
await page.locator('#themeRankMode').selectOption('both');await page.locator('#themeIconSize').evaluate(e=>e.value='3');await page.locator('#themeIconSize').dispatchEvent('input');await aligned(page);await page.screenshot({path:path.join(os.tmpdir(),'yt-v084-aligned-both.png')});await page.locator('#themeIconSize').evaluate(e=>e.value='1.5');await page.locator('#themeIconSize').dispatchEvent('input');await page.locator('#studioMockTen').uncheck();await page.locator('#themeRankMode').selectOption('icon');await aligned(page);
const iconText=el=>getComputedStyle(el,'::before').content;
assert.equal(await page.locator('#studioPreview .rank-1 .rank-icon').evaluate(iconText),'"👑"');assert.equal(await page.locator('#studioPreview .rank-1 .rank-number-text').isVisible(),false);
await page.locator('#removeRankIcon2').click();assert.equal(await page.locator('#studioPreview .rank-2 .rank-number-text').isVisible(),true);await page.locator('#defaultRankEmoji2').click();
await page.locator('#applyTheme').click();await page.locator('#studioSavedState').filter({hasText:'已儲存'}).waitFor();await obs.waitForFunction(()=>getComputedStyle(document.querySelector('.rank-1 .rank-icon'),'::before').content.includes('👑'));assert.equal(await obs.locator('.rank-3 .rank-icon').evaluate(iconText),'"👩🏽‍🚀"');
await aligned(obs);await obs.screenshot({path:path.join(os.tmpdir(),'yt-v084-aligned-obs.png')});
await page.screenshot({path:path.join(os.tmpdir(),'yt-v065-emoji-editor.png')});

for(const tab of ['content','text','layout']){await page.locator('#editor-tab-'+tab).click();assert.equal(await page.locator('.board-editor-panel:visible').count(),1);}
for(const width of [1280,850,700,375]){await page.setViewportSize({width,height:900});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'editor width '+width);await page.waitForFunction(()=>{const b=document.querySelector('#studio .creator-delivery').getBoundingClientRect(),m=document.querySelector('main');return Math.abs(b.bottom-innerHeight)<2&&Math.abs(b.left-Math.max(0,m.getBoundingClientRect().left))<2&&parseFloat(getComputedStyle(m).paddingBottom)>=b.height;});}
await page.setViewportSize({width:1280,height:900});await page.evaluate(()=>document.documentElement.style.fontSize='225%');assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.evaluate(()=>document.documentElement.style.fontSize='');
await page.reload();await page.locator('#backgroundNotice[data-state=ready]').waitFor();await page.locator('[data-tab=settings]').click();await page.locator('[data-board="sc:monthly"] .board-edit').click();assert.equal(await page.locator('#rankEmoji1').inputValue(),'👑');assert.equal(await page.locator('#rankEmoji3').inputValue(),'👩🏽‍🚀');assert.equal(await page.locator('#studioTop').inputValue(),'5');assert.equal(await page.locator('#themeTitle_monthly').inputValue(),'Custom SC');
await page.locator('[data-tab=records]').click();await page.locator('#historyImportPanel > summary').click();await page.locator('#historyRead').click();await page.locator('[data-history-live="history0003"]').waitFor();assert.equal(videoLookups,0);assert.equal(runtime.events.length,10);
const firstCard=page.locator('[data-history-card="history0001"]');await page.locator('[data-history-view="history0001"]').click();assert.equal(await page.locator('[data-history-live="history0001"]').isChecked(),false);assert.equal(await page.locator('[data-history-card]:visible').count(),1);await page.locator('#historySelectAll').click();assert.equal(await page.locator('[data-history-live]:checked').count(),3);await page.locator('#historySelectNone').click();assert.equal(await page.locator('[data-history-live]:checked').count(),0);
for(const i of [1,2,3])await page.locator('[data-history-live="history000'+i+'"]').check();
await page.locator('#historyConfirmed').check();assert.equal(await page.locator('#historyCommit').isDisabled(),true);assert.equal(await page.locator('#historyLookupSelected').isDisabled(),true);
await page.locator('#historyLookupConsent').check();await page.locator('#historyLookupSelected').click();await page.locator('#historyLookupNotice').filter({hasText:'查詢完成'}).waitFor();assert.equal(videoLookups,3);assert.equal(runtime.events.length,10);
assert.equal(await page.locator('[data-history-card="history0001"] strong').innerText(),'Public title 1');
assert.match(await page.locator('[data-history-card="history0001"]').textContent(),/本機原標題：Local archived title 1/);
assert.equal(await page.locator('.history-verification-match').count(),1);assert.equal(await page.locator('.history-verification-mismatch').count(),1);assert.equal(await page.locator('.history-verification-unknown').count(),1);
assert.equal(await page.locator('[data-history-live="history0002"]').isDisabled(),true);assert.equal(await page.locator('[data-history-live="history0002"]').isChecked(),false);
await page.locator('#historyConfirmed').check();assert.equal(await page.locator('#historyCommit').isDisabled(),true);
await page.locator('[data-history-view="history0003"]').click();await page.locator('[data-history-manual="history0003"]').check();await page.locator('[data-history-view="history0001"]').click();assert.equal(await page.locator('[data-history-manual="history0003"]').isChecked(),true);assert.equal(await page.locator('#historyCommit').isEnabled(),true);
await page.locator('#historySessions').screenshot({path:path.join(os.tmpdir(),'yt-v072-history-preview.png')});for(const width of [850,375]){await page.setViewportSize({width,height:900});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'history width '+width);}await page.setViewportSize({width:1280,height:900});
await page.locator('#historyCommit').click();await page.locator('#historyNotice').filter({hasText:'已完成 2 場'}).waitFor();assert.equal(runtime.events.length,12);assert.equal(Lock.allows(runtime.view().settings.channelLock,'history0002'),false);
await page.reload();await page.locator('#backgroundNotice[data-state=ready]').waitFor();await page.locator('[data-tab=records]').click();await page.locator('#historyImportPanel > summary').click();await page.locator('#historyRead').click();await page.locator('[data-history-live="history0003"]').waitFor();assert.equal(await page.locator('#historyLookupConsent').isChecked(),false);assert.equal(videoLookups,3);assert.equal(await page.locator('.history-verification-unchecked').count(),3);
await page.locator('#sessionsJoined').click();const row=()=>page.locator('[data-session-id="history0001"]');assert.equal(await row().locator('strong').innerText(),'Local archived title 1');const count=runtime.events.length;
for(let i=0;i<2;i++){await row().locator('button').click();await page.locator('#sessionDetail [data-session-operation=remove]').click();await page.locator('#sessionManagerNotice').filter({hasText:'已移出統計'}).waitFor();await page.locator('#sessionsOther').click();assert.match(await row().innerText(),/已移出/);await row().locator('button').click();await page.locator('#sessionDetail [data-session-operation=join]').click();await page.locator('#sessionManagerNotice').filter({hasText:'已加入統計'}).waitFor();await page.locator('#sessionsJoined').click();assert.equal(await row().count(),1);assert.equal(runtime.events.length,count);}
await page.locator('[data-session-view="live0000001"]').click();await page.locator('#sessionDetail').getByRole('button',{name:'查詢資訊'}).click();await page.locator('#sessionManagerNotice').filter({hasText:'請先勾選'}).waitFor();assert.equal(videoLookups,3);await page.locator('#sessionLookupConsent').check();await page.locator('#sessionDetail').getByRole('button',{name:'查詢資訊'}).click();await page.locator('#sessionManagerNotice').filter({hasText:'影片資訊已存於本機'}).waitFor();assert.equal(videoLookups,4);assert.equal(runtime.view().settings.channelLock.videoCatalog.live0000001.title,'Public title 1');assert.equal(runtime.events.length,count);
await page.locator('#sessionsOther').click();await page.locator('#sessionAllMonths').click();await page.locator('[data-session-view="history0002"]').click();assert.equal(await page.locator('#sessionDetail [data-session-operation=join]').isDisabled(),true);await page.locator('#sessionSearch').fill('Public title 2');assert.equal(await page.locator('#sessionRows .session-row').count(),1);await page.locator('#sessionSearch').fill('');await page.setViewportSize({width:375,height:900});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.setViewportSize({width:1280,height:900});
// 300 synthetic sessions, two years, pending and excluded records. No real data.
await runtime.subscribe('comments',Array.from({length:300},(_,i)=>({service:'youtube',data:{type:'superchat',id:'scale-'+i,userId:'scale-'+i,name:'Scale '+i,liveId:'scale'+String(i).padStart(6,'0'),streamTitle:'隔離測試直播 '+i+'｜跨年場次整理',timestamp:i<150?'2025-12-15T12:00:00Z':'2026-01-15T12:00:00Z',price:10,unit:'TWD'}})));
await page.evaluate(()=>load());await page.locator('#sessionAllMonths').click();await page.locator('#sessionSearch').fill('scale');assert.equal(await page.locator('#sessionRows .session-row').count(),20);assert.match(await page.locator('#sessionPageInfo').textContent(),/1 \/ 15 頁 · 300 場/);await page.locator('#sessionNext').click();assert.match(await page.locator('#sessionPageInfo').textContent(),/2 \/ 15/);
await page.locator('#sessionYear').selectOption('2025');await page.locator('#sessionMonth').selectOption('12');assert.match(await page.locator('#sessionPageInfo').textContent(),/150 場/);await page.locator('#sessionSearch').fill('scale000299');assert.equal(await page.locator('#sessionRows .session-row').count(),0);await page.locator('#sessionAllMonths').click();assert.equal(await page.locator('#sessionRows .session-row').count(),1);await page.locator('#sessionSearch').fill('');await page.locator('#sessionStatus').selectOption({label:'其他頻道'});assert.equal(await page.locator('#sessionRows .session-row').count(),1);await page.locator('#sessionStatus').selectOption({label:'待確認'});assert.equal(await page.locator('#sessionRows .session-row').count(),20);await page.locator('#sessionRows button').first().click();assert.equal(await page.locator('#sessionDetail h4').count(),1);
await page.locator('#historyImportPanel > summary').click();await page.locator('#sessionManager').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(os.tmpdir(),'yt-v081-session-manager-dark.png')});
await runtime.subscribe('services',[{id:'unknown-date',url:'https://www.youtube.com/watch?v=unknown0001',enabled:true}]);await runtime.subscribe('comments',[{service:'youtube',data:{type:'superchat',id:'excluded-test',userId:'excluded-test',name:'Test excluded',liveId:V,timestamp:new Date().toISOString(),isTest:true,price:10,unit:'TWD'}}]);await page.evaluate(()=>load());await page.locator('#sessionStatus').selectOption('');await page.locator('#sessionYear').selectOption('unknown');assert.equal(await page.locator('#sessionRows .session-row').count(),2);assert.equal(await page.locator('#sessionMonth').isDisabled(),true);assert.equal(await page.locator('[data-session-view="unknown0001"]').count(),1);
const beforeFilter=JSON.stringify(runtime.events),beforeStyles=JSON.stringify(runtime.styles);
await page.locator('[data-tab=events]').click();await page.locator('#eventStatusFilter').selectOption('pending');assert.equal(await page.locator('#compactEventRows .event-status').count(),25);assert.deepEqual([...new Set(await page.locator('#compactEventRows .event-status').allTextContents())],['待核對']);await page.locator('#eventStatusFilter').selectOption('counted');assert.equal(await page.locator('#compactEventRows .event-status').count(),12);await page.locator('#eventStatusFilter').selectOption('excluded');assert.equal(await page.locator('#compactEventRows .event-status').count(),1);assert.equal(await page.locator('#compactEventRows .event-status').innerText(),'不計入');await page.getByRole('button',{name:'清除篩選',exact:true}).click();assert.equal(await page.locator('#eventStatusFilter').inputValue(),'');
await page.locator('#eventStatusFilter').selectOption('pending');await page.locator('#compactEventRows button').first().click();assert.equal(await page.locator('#eventDetail').evaluate(e=>getComputedStyle(e).backgroundColor),'rgb(27, 34, 46)');await page.locator('#eventDetail button').click();
await page.screenshot({path:path.join(os.tmpdir(),'yt-v081-events-dark.png')});await page.locator('#managementTheme').selectOption('light');await page.screenshot({path:path.join(os.tmpdir(),'yt-v081-events-light.png')});assert.equal(JSON.stringify(runtime.events),beforeFilter);assert.equal(JSON.stringify(runtime.styles),beforeStyles);
await page.locator('[data-tab=settings]').click();await page.locator('[data-board="sc:monthly"] .board-edit').click();const previewStyle=()=>page.locator('#studioPreview .rank-title').evaluate(e=>[getComputedStyle(e).color,getComputedStyle(e).fontFamily,getComputedStyle(e).backgroundColor]);const unchanged=await previewStyle();await page.locator('#managementTheme').selectOption('dark');assert.deepEqual(await previewStyle(),unchanged);await page.screenshot({path:path.join(os.tmpdir(),'yt-v081-editor-dark.png')});
await page.locator('#editor-tab-text').click();await page.locator('.font-picker-button:visible').first().click();assert.equal(await page.locator('.creator-font-dialog').evaluate(e=>getComputedStyle(e).color),'rgb(232, 237, 245)');await page.locator('.creator-font-dialog [data-close]').click();for(const width of [850,375]){await page.setViewportSize({width,height:900});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'dark theme width '+width);}
assert.deepEqual(errors,[]);assert.deepEqual(external,[]);console.log(JSON.stringify({ok:true,checks:['session remove / restore twice / no duplicate / foreign blocked / title cache / search / narrow','history match / mismatch / manual / import / F5','channel lookup consent / confirm / F5','seven pages','nine boards','no old selectors','legacy URL 3 -> saved 5','copy keeps target title','three tabs','narrow editor / 200% text','F5','no external requests']}));
}finally{await browser?.close();server.closeAllConnections();await new Promise(r=>server.close(r));await runtime.close();await fsp.rm(dir,{recursive:true,force:true});}
})().catch(e=>{console.error(e);process.exitCode=1;});
