'use strict';
const crypto=require('node:crypto'),Policy=require('../record-policy'),Lock=require('../channel-lock'),{normalizeEvent}=require('./core');
const {readCommentDatabase}=require('./history-sqlite');
const clone=x=>JSON.parse(JSON.stringify(x));
function dateRange(from,to){const valid=v=>typeof v==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(v)&&new Date(v+'T00:00:00Z').toISOString().slice(0,10)===v;if(!valid(from)||!valid(to))throw Error('請選擇有效的開始與結束日期');const first=Date.parse(from+'T00:00:00+08:00'),until=Date.parse(to+'T00:00:00+08:00')+86400000;if(until<=first||until-first>366*86400000)throw Error('日期範圍須為 1 至 366 天');return {from:new Date(first).toISOString(),until:new Date(until).toISOString()};}
function parseLogFiles(files){if(!Array.isArray(files)||!files.length||files.length>30)throw Error('請選擇 1 至 30 份日誌檔');const rows=[];let bytes=0;for(const f of files){if(!f||typeof f.text!=='string')throw Error('日誌內容無效');bytes+=Buffer.byteLength(f.text);if(bytes>64*1024*1024)throw Error('日誌總量不可超過 64 MB');const name=String(f.name||'日誌').slice(0,100),text=f.text.replace(/^\uFEFF/,'').trim();if(!text)continue;try{if(text.startsWith('[')){const items=JSON.parse(text);if(!Array.isArray(items))throw Error();for(const item of items)rows.push(item);}else{let n=0;for(const line of text.split(/\r?\n/)){n++;if(!line.trim())continue;if(Buffer.byteLength(line)>1024*1024)throw Error('第 '+n+' 行過大');try{rows.push(JSON.parse(line));}catch{throw Error('第 '+n+' 行不是有效 JSON');}}}}catch(e){throw Error(name+'：'+(e.message||'無法解析日誌'));}if(rows.length>250000)throw Error('單次最多讀取 250,000 則紀錄，請減少檔案');}return rows;}
function timestamp(value){if(typeof value==='number'&&Number.isFinite(value)&&value>=0&&value<8640000000000000)return new Date(value).toISOString();return typeof value==='string'?value:'';}
function titleOf(item){const d=item.data||{},m=item.meta||{};const value=d.streamTitle??d.videoTitle??m.streamTitle??m.title??'';return typeof value==='string'?value.slice(0,200):'';}
function collect(rows,settings,range){if(!Array.isArray(rows))throw Error('紀錄格式不正確');const sessions=new Map();let skipped=0,invalid=0,totalBytes=0,eventCount=0;for(const raw of rows){if(!raw||typeof raw!=='object'||!raw.data||typeof raw.data!=='object'||Array.isArray(raw.data)){invalid++;continue;}if(raw.service!=='youtube'){skipped++;continue;}const item={...raw,data:{...raw.data}},d=item.data;d.timestamp=timestamp(d.timestamp??item.timestamp);const time=Date.parse(d.timestamp);if(!Number.isFinite(time)){invalid++;continue;}if(time<Date.parse(range.from)||time>=Date.parse(range.until))continue;const rawLive=d.liveId??item.liveId,byId=Lock.parseLive(rawLive),byUrl=Lock.parseLive(item.url);if(byId&&byUrl&&byId!==byUrl){invalid++;continue;}if(rawLive==='youtube-test')d.isTest=true;const liveId=byId||byUrl;if(!liveId){invalid++;continue;}d.liveId=liveId;const title=titleOf(item);let group=sessions.get(liveId);if(!group){group={liveId,title,firstRecorded:d.timestamp,lastRecorded:d.timestamp,startedAt:'',events:[],messages:0};sessions.set(liveId,group);}group.messages++;if(!group.title&&title)group.title=title;if(time<Date.parse(group.firstRecorded))group.firstRecorded=d.timestamp;if(time>Date.parse(group.lastRecorded))group.lastRecorded=d.timestamp;const started=timestamp(d.startedAt??item.meta?.startedAt);if(Policy.validTimestamp(started))group.startedAt=started;
 const event=normalizeEvent(item,{streamTitle:title},settings);if(event.unsupported){skipped++;continue;}event.importSource='onecomme-history';totalBytes+=Buffer.byteLength(JSON.stringify(event));if(totalBytes>32*1024*1024||eventCount>=50000)throw Error('支持紀錄過多，請縮小日期範圍');group.events.push(event);eventCount++;
 }return {sessions:[...sessions.values()].filter(g=>g.events.length),skipped,invalid};}
function identity(e){return JSON.stringify([e.service,e.liveId,e.eventId]);}
function merge(events,incoming){const buckets=new Map();for(const e of events){const key=identity(e);if(!buckets.has(key))buckets.set(key,[]);buckets.get(key).push(e);}let added=0,duplicates=0,updated=0;for(const e of incoming){const key=identity(e);let bucket=buckets.get(key);if(!bucket){bucket=[];buckets.set(key,bucket);}const before=bucket.length;if(Policy.ingest(bucket,e)){if(bucket.length>before){events.push(e);added++;}else updated++;}else duplicates++;}return {added,duplicates,updated};}
function configKey(saved){const {videoCatalog,...lock}=saved.settings.channelLock;return JSON.stringify([{...saved.settings,channelLock:lock},saved.reset]);}
function createHistoryImport({readDatabase=readCommentDatabase,now=Date.now,resolveVideo=require('./youtube-resolver').resolveVideoUrl}={}){let scan=null,looking=false,nextLookup=0;
 function current(body,saved){if(!scan||body.token!==scan.token||now()-scan.at>600000)throw Error('匯入預覽已過期，請重新讀取紀錄');if(scan.config!==configKey(saved)||body.channelId!==scan.channelId)throw Error('頻道或統計設定已變動，請重新預覽');return scan;}
 function snapshot(value){return {...value.view,sessions:value.entries.map(entry=>{const verification=clone(value.checks.get(entry.liveId)||{status:'unchecked'});return {...entry,verification,videoUrl:'https://www.youtube.com/watch?v='+entry.liveId,blocked:entry.blocked||(verification.status==='mismatch'?'YouTube 顯示此影片屬於其他頻道，不能匯入目前頻道。':'')};})};}
 async function lookup(body,getSaved){
  if(body.consent!==true)throw Error('請先同意向 YouTube 查詢影片公開資料');
  const active=current(body,getSaved());
  if(!active.groups.some(g=>g.liveId===body.liveId))throw Error('影片不在本次預覽內');
  if(looking||now()<nextLookup)throw Error('請稍候一秒再查詢；同時只查一支影片');
  const cached=active.checks.get(body.liveId);if(cached?.status==='match'||cached?.status==='mismatch')return snapshot(active);
  looking=true;nextLookup=now()+1000;
  try{
   let check;
   try{const url='https://www.youtube.com/watch?v='+body.liveId,r=require('../public-resolver').validate(url,await resolveVideo(url));check={...r,status:r.channelId===active.channelId?'match':'mismatch'};}
   catch(e){check={status:'unknown',reason:String(e.message||'查詢失敗').slice(0,300)};}
   if(current(body,getSaved())!==active)throw Error('預覽已更新，舊查詢結果未套用');
   active.checks.set(body.liveId,check);return snapshot(active);
  }finally{looking=false;}
 }

 async function preview(body,saved){scan=null;const range=dateRange(body.from,body.to);if(!saved.settings.channelLock.channelId)throw Error('請先在「頻道與直播」設定要統計的實況主');let rows;if(body.source==='database')rows=await readDatabase(range);else if(body.source==='files')rows=parseLogFiles(body.files);else throw Error('不支援的紀錄來源');const result=collect(rows,saved.settings,range);const reset=e=>!!saved.reset.at&&(saved.reset.ids.includes(e.eventId)||!Number.isFinite(Date.parse(e.timestamp))||Date.parse(e.timestamp)<=saved.reset.at);const entries=result.sessions.map(g=>{let proposed,blocked='';try{proposed=Lock.bind(saved.settings.channelLock,g.liveId);}catch(e){blocked=e.message;}const events=clone(g.events),existing=clone(saved.events.filter(e=>e.liveId===g.liveId&&e.service==='youtube'));const stats=merge(existing,events);return {liveId:g.liveId,title:g.title,firstRecorded:g.firstRecorded,lastRecorded:g.lastRecorded,startedAt:g.startedAt,messages:g.messages,supports:g.events.length,sc:g.events.filter(e=>['superchat','supersticker'].includes(e.eventType)).length,gift:g.events.filter(e=>e.eventType==='sponsorgift').length,jewel:g.events.filter(e=>e.eventType==='jewel').length,received:g.events.filter(e=>e.eventType==='giftreceived').length,eligible:blocked?0:events.filter(e=>Policy.eligible(e,reset,proposed)).length,...stats,blocked,needsConfirmation:!Lock.allows(saved.settings.channelLock,g.liveId),samples:events.slice(0,12).map(e=>({name:e.displayName,type:e.eventType,time:e.timestamp,value:e.eventType==='sponsorgift'?e.giftCount+' 個':e.eventType==='jewel'?e.jewelTotal+' 顆':e.eventType==='giftreceived'?'受贈（不計贈送榜）':e.originalAmount+' '+(e.normalizedCurrency||e.originalCurrency),status:blocked||Policy.status(e,reset,proposed)}))};});scan={token:crypto.randomBytes(24).toString('hex'),at:now(),config:configKey(saved),groups:result.sessions,channelId:saved.settings.channelLock.channelId,entries,checks:new Map()};scan.view={token:scan.token,channelId:scan.channelId,channelName:saved.settings.channelLock.channelName,skipped:result.skipped,invalid:result.invalid,recordMode:saved.settings.recordMode||'production',range};return snapshot(scan);}
 function prepare(body,saved){current(body,saved);if(looking)throw Error('影片查詢中，請等待結果後再匯入');if(body.confirmed!==true)throw Error('請先確認所選直播屬於目前鎖定頻道');if(!Array.isArray(body.liveIds)||!body.liveIds.length||body.liveIds.length>200)throw Error('請選擇 1 至 200 場直播');const ids=[...new Set(body.liveIds)];const next=clone(saved),incoming=[];for(const id of ids){const group=scan.groups.find(g=>g.liveId===id);if(!group)throw Error('所選場次不在本次預覽內');const check=scan.checks.get(id);if(check?.status==='mismatch')throw Error('影片屬於其他頻道，不能匯入目前頻道');if(check?.status!=='match'&&(!Array.isArray(body.manualLiveIds)||!body.manualLiveIds.includes(id)))throw Error('未確認的影片須逐場勾選人工確認，或先查詢頻道歸屬');next.settings.channelLock=Lock.bind(next.settings.channelLock,id);for(const e of group.events)incoming.push(clone(e));}const stats=merge(next.events,incoming);return {next,stats:{...stats,sessions:ids.length,records:incoming.length}};}
 return {preview,prepare,lookup};
}
module.exports={dateRange,parseLogFiles,collect,merge,createHistoryImport};
