'use strict';
const fs=require('node:fs/promises'),path=require('node:path'),https=require('node:https'),crypto=require('node:crypto'),cp=require('node:child_process');
const REPO='Master-Asa/YT-Rank-Show',API='https://api.github.com/repos/'+REPO;
const MAX=32*1024*1024;
function version(v){if(typeof v!=='string'||!/^\d{1,5}\.\d{1,5}\.\d{1,5}$/.test(v))throw Error('版本格式不符');return v.split('.').map(Number);}
function newer(a,b){const x=version(a),y=version(b);for(let i=0;i<3;i++){if(x[i]!==y[i])return x[i]>y[i];}return false;}
function allowed(raw){const u=new URL(raw);if(u.protocol!=='https:'||u.username||u.password||u.port||!['api.github.com','github.com','release-assets.githubusercontent.com','objects.githubusercontent.com'].includes(u.hostname))throw Error('拒絕非 GitHub 更新來源');return u;}
function download(raw,limit=MAX,redirects=0){return new Promise((resolve,reject)=>{let u;try{u=allowed(raw);}catch(e){return reject(e);}const req=https.get(u,{headers:{'User-Agent':'YT-Rank-Show-Updater','Accept':'application/vnd.github+json'}},res=>{if([301,302,303,307,308].includes(res.statusCode)){res.resume();if(redirects>=5)return reject(Error('更新下載重新導向過多'));let next;try{next=new URL(res.headers.location,u).href;}catch{return reject(Error('更新網址無效'));}return download(next,limit,redirects+1).then(resolve,reject);}if(res.statusCode!==200){res.resume();return reject(Error(res.statusCode===404?'目前無法讀取公開版本；儲存庫可能尚未公開。':res.statusCode===403||res.statusCode===429?'GitHub 暫時限制查詢，請稍後再試。':'GitHub 下載失敗（'+res.statusCode+'）'));}let n=0;const chunks=[];res.on('data',b=>{n+=b.length;if(n>limit){req.destroy(Error('更新檔案超過大小限制'));return;}chunks.push(b);});res.on('end',()=>resolve(Buffer.concat(chunks)));res.on('error',reject);});const timer=setTimeout(()=>req.destroy(Error('GitHub 連線逾時')),45000);req.on('close',()=>clearTimeout(timer));req.on('error',reject);});}
function candidate(releases,current){if(!Array.isArray(releases))throw Error('GitHub 版本資料不符');const found=[];for(const r of releases){if(r.draft||r.prerelease||!/^v\d{1,5}\.\d{1,5}\.\d{1,5}$/.test(r.tag_name||''))continue;const v=r.tag_name.slice(1);if(!newer(v,current))continue;const name='YT-Rank-Show-'+v+'-Windows.zip',assets=(r.assets||[]).filter(a=>a.name===name&&a.state==='uploaded');if(assets.length!==1)continue;const a=assets[0];if(!Number.isSafeInteger(a.size)||a.size<1||a.size>MAX||!/^sha256:[a-f0-9]{64}$/.test(a.digest||'')||a.browser_download_url!=='https://github.com/'+REPO+'/releases/download/v'+v+'/'+name)continue;found.push({version:v,url:a.browser_download_url,sha256:a.digest.slice(7),size:a.size,notes:String(r.body||'').slice(0,12000)});}return found.sort((a,b)=>newer(a.version,b.version)?-1:1)[0]||null;}
const ps=()=>path.join(process.env.SystemRoot||'C:\\Windows','System32','WindowsPowerShell','v1.0','powershell.exe');
async function createUpdater({dir,pluginDir=path.resolve(__dirname,'..'),current=require('../app-version'),get=download,launch,prepare,now=Date.now,autoStart=true}={}){
 await fs.mkdir(dir,{recursive:true});let prefs={automatic:false},last=0,busy=false,closed=false,offer=null,prepared=null,handed=null,error='',phase='idle';
 const prefFile=path.join(dir,'preferences.json');try{const p=JSON.parse(await fs.readFile(prefFile,'utf8'));prefs.automatic=p.automatic===true;}catch{}
 function status(){if(phase==='waiting'&&handed){try{const raw=require('node:fs').readFileSync(path.join(handed,'result.json'),'utf8');if(raw.length<8192){const r=JSON.parse(raw.replace(/^\ufeff/,''));if(r.state==='cancelled'){prepared=handed;handed=null;phase='ready';error='已取消安裝；可重新開啟更新視窗。';}else if(r.state==='failed'){prepared=null;handed=null;phase='idle';error='上次安裝未完成，請查看更新視窗或 result.json，確認舊版後再試。';}}}catch{}}return {current,automatic:prefs.automatic,busy,phase,lastChecked:last,error,available:offer?{version:offer.version,notes:offer.notes}:null,ready:!!prepared};}
 async function exclusive(fn){if(busy||phase==='waiting')throw Error('更新作業進行中');busy=true;let result;try{error='';result=await fn();}catch(e){error=e.message;phase=prepared?'ready':'idle';throw e;}finally{busy=false;}return {...result,busy:false};}
 async function check(){return exclusive(async()=>{phase='checking';const selected=candidate(JSON.parse((await get(API+'/releases?per_page=100',2*1024*1024)).toString('utf8')),current);if(closed)return status();if(!selected||offer?.sha256!==selected.sha256)prepared=null;offer=selected;last=now();phase=prepared?'ready':'idle';return status();});}
 async function savePrefs(automatic){prefs.automatic=automatic===true;const tmp=prefFile+'.tmp';await fs.writeFile(tmp,JSON.stringify(prefs));await fs.rename(tmp,prefFile);return status();}
 async function stage(){return exclusive(async()=>{if(!offer)throw Error('請先檢查新版');const chosen={...offer};phase='downloading';prepared=null;const bytes=await get(chosen.url);if(bytes.length!==chosen.size||crypto.createHash('sha256').update(bytes).digest('hex')!==chosen.sha256)throw Error('更新包驗證失敗，未更動舊版');if(closed)throw Error('插件正在關閉，請重新下載');const task=await fs.mkdtemp(path.join(dir,'update-'));await fs.writeFile(path.join(task,'package.zip'),bytes,{flag:'wx'});await fs.writeFile(path.join(task,'update-install.ps1'),'\ufeff'+(await fs.readFile(path.join(pluginDir,'scripts','update-install.ps1'),'utf8')).replace(/^\ufeff/,''));const plan={version:chosen.version,sha256:chosen.sha256};await fs.writeFile(path.join(task,'plan.json'),JSON.stringify(plan));if(prepare)await prepare(task);else await new Promise((resolve,reject)=>cp.execFile(ps(),['-NoProfile','-NonInteractive','-ExecutionPolicy','Bypass','-File',path.join(task,'update-install.ps1'),'-PrepareOnly'],{cwd:task,windowsHide:true,timeout:120000},e=>e?reject(Error('更新包解壓或內容檢查失敗，未更動舊版')):resolve()));prepared=task;phase='ready';return status();});}
 async function install(){return exclusive(async()=>{if(!prepared)throw Error('請先下載並驗證更新包');if(phase==='waiting')throw Error('更新視窗已開啟');const expected=path.resolve(process.env.APPDATA||'', 'onecomme','plugins','local.yt-rank-show.plugin');if(!launch&&path.resolve(pluginDir).toLowerCase()!==expected.toLowerCase())throw Error('請在正式安裝的 OneComme 插件中啟動更新');await fs.writeFile(path.join(prepared,'result.json'),JSON.stringify({state:'launching'}));if(launch)await launch(prepared);else await new Promise((resolve,reject)=>{const child=cp.spawn(ps(),['-NoProfile','-STA','-ExecutionPolicy','Bypass','-File',path.join(prepared,'update-install.ps1')],{cwd:prepared,detached:true,windowsHide:true,stdio:'ignore'});child.once('error',reject);child.once('spawn',()=>{child.unref();resolve();});});handed=prepared;phase='waiting';prepared=null;return status();});}
 const tick=()=>{if(!closed&&prefs.automatic&&!busy&&phase!=='waiting'&&now()-last>6*60*60*1000){last=now();check().catch(()=>{});}};
 const timer=autoStart?setInterval(tick,60000):null;timer?.unref();if(autoStart)tick();
 return {status,check,stage,install,savePrefs,close(){closed=true;if(timer)clearInterval(timer);},tick};
}
module.exports={createUpdater,candidate,newer,allowed,download};
